### PR TITLE
fix #1048 Detect Context trigger object in repeatWhen/retryWhen

### LINKED ISSUE #1048: retryWhen/repeatWhen should support Context injection
Currently `retryWhen` and `repeatWhen` can accept an Object signal to trigger the resubscribe flow. We could check if the companion object is of type `Context` to inject it on resubscribe.

This might be useful to keep track of state between multiple retries/repeat in the upstream flow.

### PR DESCRIPTION
**Pull request by simonbasle**
@smaldini is that what you had in mind for #1048? (see the tests)

### CODE REVIEW

**Comment by smaldini** [comment]
Very nice, I wouldn't go as far as putting all since it could override keys you don't want. The user can still use 
```retryWhen(errors -> Mono.subscriberContext()
                                             .flatMap(ctx -> errors.map(e -> ctx.putAll(Context.of(xxx)))
```

**Comment by simonbasle** [comment]
so you mean you'd completely replace the old `Context`? currently it keeps the old `Context` and overwrites the keys that are present in the `Context` created as part of the `repeatWhen` inner chain.

So for instance this:
```java
Flux<String> retryWithContext =
				Flux.just("A", "B")
				    .retryWhen(errorFlux -> errorFlux.map(error -> Context.of("foo", "baz"))
				                                     .take(2)
				                                     .concatWith(Mono.error(new IllegalStateException("retries exhausted"))))
				    .subscriberContext(Context.of("bamboozle", "false"))
				    .subscriberContext(Context.of("foo", "bar"));
```

would only change the `foo` entry. Context would still contain `bamboozle=false` on every retry.

**Comment by simonbasle** [comment]
@smaldini I initially modified it to replace by default, but came up with this intermediate solution of a special key in the companion `Context`, because I strongly think the replace-by-default behaviour _will_ lead to users unknowingly shooting themselves in the foot.

So in the latest commit, we do a `currentContext = currentContext.putAll(companionContext)` by default (which preserves values set downstream by eg. a framework).

If the user wants to only keep keys she explicitly set in her companion `Context`, putting a special key `Context.CONTEXT_REPLACE` in it will do the trick.

wdyt?

**Comment by smaldini** [comment]
Nah i don't think that adding a special key will be less convoluted, the simplest approach is to emit what the user emits and if it's a new context (unlikely for context mutations), then emit it. Its equally surprising to omit keys as it is to append ones depending on where you come from. Also what if you want to remove keys.

**Comment by simonbasle** [comment]
That's where I don't agree... It has much more dangerous implications if the default / easiest path leads to unknowingly dropping keys. If you want to remove keys, then it should involve more boilerplate, because you need to be absolutely sure of what you're doing.

Pinging @rwinch @rstoyanchev for their opinion.

**Comment by smaldini** [comment]
The use case for enriching a context should be an explicit operation. The operator subscriberContext(fn) behaves the same as the intent I would prefer to give here. It boils down to the immutable aspect, we should implicitly discourage context Reactor changes and “do what you see”. Again it’s pretty niche to emit a context in retryWhen/repeatWhen but when we do we usually work with the previous context, emitting a new context as in the test is something that shouldn’t be a recurrent situation within this niche behavior.

**Comment by simonbasle** [comment]
@rwinch FYI we'll go the REPLACE way, @smaldini's preference. I added a big warning and a code example on how to correctly use that feature without breaking libraries that depend on the Context in the javadoc. It'd be perfect if you could take a quick glance today and tell if you think this is a good middle ground. Otherwise I'll merge this tomorrow CET.

**Pull request merged**
