### PR TITLE
Update gettingStarted.adoc

### PR DESCRIPTION
**Pull request by tomasz-galuszka**
Updated forgo to forgot

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tomasz-galuszka Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1780)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1780) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tomasz-galuszka Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1780)!

**Comment by bsideup** [comment]
Hi @tomasz-galuszka,

Thanks for finding time, but this is not a typo :)
https://dictionary.cambridge.org/dictionary/english/forgo

**Comment by tomasz-galuszka** [comment]
Crap... sorry - I was reading it too fast so my mistake.

Cheers,
Tom

**Comment by bsideup** [comment]
@tomasz-galuszka no problem :) Thanks for willing to help! 👍

**Pull request closed without merging**
