### PR TITLE
adds cancellation of the source future support

### LINKED ISSUE #3138: Propagate cancel signal on Mono to wrapped CompletableFuture
Currently, `Mono#fromFuture` uses `MonoCompletionStage`, and `CompletionStage` does not have a `cancel` method. As a result, even if the `Mono` is cancelled, the future is never made aware of it.

### PR DESCRIPTION
**Pull request by OlegDokuka**
closes #3138

Signed-off-by: Oleh Dokuka <odokuka@vmware.com>

### CODE REVIEW

**Review by chemicL — APPROVED** [review]

**Review by simonbasle — APPROVED** [review]
this will likely cause some conflict when merging into main, but not too hard to solve. feel free to merge this @OlegDokuka 👍

**Comment by simonbasle** [comment]
merged into `3.5.0-M6` via commit https://github.com/reactor/reactor-core/commit/ebfc60ab1de66aafe05fd85b9630e4f55dc8cd59

**Comment by steven-sheehy** [comment]
I believe the `Mono.fromFuture()` docs are now incorrect after this change:

```
Note that the future is not cancelled when that Mono is cancelled, but that behavior can be obtained by using a doFinally(Consumer) that checks for a SignalType.CANCEL and calls CompletableFuture.cancel(boolean).
```

**Comment by simonbasle** [comment]
> I believe the `Mono.fromFuture()` docs are now incorrect after this change:
> 
> ```
> Note that the future is not cancelled when that Mono is cancelled, but that behavior can be obtained by using a doFinally(Consumer) that checks for a SignalType.CANCEL and calls CompletableFuture.cancel(boolean).
> ```

that's a good point 👍 
do you want to submit a doc PR to `3.4.x` branch @steven-sheehy ?

**Pull request merged**
