### PR TITLE
Add take(int, boolean), prep for new default behavior in 3.5

### LINKED ISSUE #2339: Flux#limitRequest vs Flux#take
I was expecting `Flux#limitRequest` to not cancel upstream when the request is fulfilled (otherwise, it is unclear why it exists when `Flux#take` does essentially the same).

The following snippet demonstrates the problem:
```java
Flux.range(0, 10)
    .log("range")
    .limitRequest(2)
    .log("limitRequest")
    .blockLast();
```

The output:
```
17:58:11.359 [main] INFO  limitRequest - request(unbounded)
17:58:11.359 [main] INFO  range - | request(2)
17:58:11.359 [main] INFO  range - | onNext(0)
17:58:11.359 [main] INFO  limitRequest - onNext(0)
17:58:11.359 [main] INFO  range - | onNext(1)
17:58:11.359 [main] INFO  limitRequest - onNext(1)
17:58:11.360 [main] INFO  range - | cancel() <-- cancelled right after receiving onNext(1)
17:58:11.360 [main] INFO  limitRequest - onComplete()
```

We should either deprecate `limitRequest` in favour of (more logical) `Flux#take` or make it not cancel.

### PR DESCRIPTION
**Pull request by simonbasle**
This commit introduces the `takeEager` operator and makes `take` an
alias for it. `takeEager` is the new canonical way of obtaining the
current take behavior (unbounded upstream request, cancels when enough
elements have been emitted).

Furthermore, it reflects in `take` javadoc that the behavior will change
in 3.5.0 so that `take` becomes the new official name for `limitRequest`
behavior (still cancel whenever enough elements have been emitted,
but limit the upstream request to what is strictly necessary).
See #2690 for planned changes.

Fixes #2339.

### CODE REVIEW

**Comment by OlegDokuka** [comment]
just thinking, what if we add extra param to the `take` operator. e.g.:

```java
public Flux<T> take(long n) {
	return take(n, true); // by default true with future replacement to false
} 

public Flux<T> take(long n, boolean fast) {
	if (fast) {
	   return takeEager(n);
	} else {
	   return limitRequest(n);
	}
}

Flux<T> takeEager(long n) // pkg private

@Deprecated
public Flux<T> limitRequest(long n)
```

**Comment by simonbasle** [comment]
@OlegDokuka agreed, updated the PR accordingly

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Comment by rstoyanchev** [comment]
The title of the PR needs an update.

**Pull request merged**
