### PR TITLE
Fixes #80. Provide Exception methods to support use of functions that…

### LINKED ISSUE #80: Consider introducing utility method for checked functions
When adopting reactor, but needing to wrap and use existing code you find yourself using try/catch blocks within `map` and other operators repeatedly which severely impacts the readability of code.  The introduction of a CheckedFunction could help with this significantly.

`Exceptions.checked(CheckedFunction) : Function`

### PR DESCRIPTION
**Pull request by dfeist**
… throw checked exceptions and implicitly propagate exceptions.

(Opening PR to share and get feedback on approach, will fill out javadoc and update method names as required based on feedback)

### CODE REVIEW

**Comment by smaldini** [comment]
Round of approval / feedback : @akarnokd , @rstoyanchev , @sdeleuze

**Comment by akarnokd** [comment]
How about having CheckedX on the operators directly? Avoids wrapping and unwrapping checked exceptions.

**Comment by smaldini** [comment]
Wait, changing all the signatures ? naaaaaaaah

**Comment by smaldini** [comment]
Plus not to forget that usually wrapping Exception stuff means you are mapping a "blocking" call which overtime shouldn't be that necessary or you would use flatMap more for that.

**Comment by dfeist** [comment]
Agree with Stephane. I argued for this being in core Exceptions and not a
seperate module,  but putting it in Flux is going too far IMO.

This will be used quite commonly but still isn't best practice and usage
should reduce gradually over time I'd hope.

**Comment by smaldini** [comment]
Closing for now, don't hesitate to port that as a standalone new addon :D

**Pull request closed without merging**
