### PR TITLE
#1240 Flux/Mono Sink `onDispose` `onCancel` to `onTerminal`

### PR DESCRIPTION
**Pull request by OlegDokuka**
See the #1240 

/cc @simonbasle @nnanda2016

### CODE REVIEW

**Comment by OlegDokuka** [comment]
WIDE CHANGES | API CHANGES | NEED DOCS CHANGES | NEED DISCUSSION

**Comment by smaldini** [comment]
I think its more an issue with doFinally in Flux.Mono. But the name fits naturally too, its just not consistent. Dispose is always cleaned regardless of the termination, Terminate is all disposing but interruption, Cancel is interruption only.

**Comment by OlegDokuka** [comment]
@simonbasle fixed

**Comment by OlegDokuka** [comment]
Cool, it is left unchanged docs, so Im going to add fixes here as well

**Comment by simonbasle** [comment]
Closing for now in favor of improving the javadoc

**Pull request closed without merging**
