### PR TITLE
Make use of CompletionStage#handle instead of `whenComplete`.

### PR DESCRIPTION
**Pull request by He-Pin**
https://github.com/reactor/reactor-core/pull/3221
For Main branch

### CODE REVIEW

**Review by simonbasle — APPROVED** [review]

**Comment by simonbasle** [comment]
I will either merge this or include this in the forward-merge of sister PR #3221

**Comment by He-Pin** [comment]
@simonbasle Do you mean backport the folding `BiFunction` into `MonoCompletionStageSubscription` to 3.4.x release?

**Comment by simonbasle** [comment]
@He-Pin no, I'll merge the other PR into 3.4.x, merge 3.4.x into `main` and use the code from this one to solve the resulting merge conflict.

**Comment by He-Pin** [comment]
I see, thanks for the detail.

**Pull request closed without merging**
