### PR TITLE
fix #2538 Let `TestLogger` be configured with static message

### LINKED ISSUE #2538: Let `TestLogger` be configured with simplified format
Currently we output the thread name, but sometimes it would be better to simplify to something static other than the message (like `[INFO ] Message`) for simplified per-line assertions.

### PR DESCRIPTION
**Pull request by vdjuketic**
Added an additional option for each log type which logs a static message.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vdjuketic Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2540)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2540) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vdjuketic Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2540)!

**Review by simonbasle — CHANGES_REQUESTED** [review]
hi @vdjuketic thanks for the effort, but that is not a all what #2538 is about. The problem is that methods like `debug(msg)` log the `msg` using a format string that starts with `[DEBUG] (%s)` where that first `%s` is the current thread name. In some cases, this dynamic value will make asserting the logged content harder.

**Comment by vdjuketic** [comment]
@simonbasle Thanks for the clarification. I'm going to close this PR and open another one with the revised code because the branch name is not according to the guidelines.

**Pull request closed without merging**
