### PR TITLE
[doc typo] Fix List ref name in hybrid push/pull code

### PR DESCRIPTION
**Pull request by yosfik**
Change from `message` to `messages`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yosfik Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2384)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2384) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by yosfik** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@yosfik This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by ericbottard** [comment]
Merged all the way up to 3.2.x, thanks for the fix @yosfik !

**Pull request merged**
