### PR TITLE
continue polishing of Flux javadoc, aligning some Mono javadocs

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by simonbasle** [comment]
preview of what the `flatMap`/`concatMap`/`flatMapIterable` javadoc alignment looks like (here concatMap):
image

**Comment by simonbasle** [comment]
☝️ I wonder if the bold part of the bullet points should reflect the actual behavior of the operator rather than be a shared text for all 3 (but keep them on a common theme, eg. put "No interleaving" for concatMap and flatMapSequential). Thoughts, @smaldini ?

**Comment by smaldini** [comment]
awesome work ! A well needed refresh

**Comment by simonbasle** [comment]
re my last comment we can improve that after M1 if need be, merged

**Pull request merged**
