### PR TITLE
#1105 Improve lift contract

### LINKED ISSUE #1105: Reconsider the `LiftFunction`/`lift` operator contract
This contract has one problem in forcing the use of `Scannable`, both in the predicate and in the application of the `lifter` function (see `MonoLift`, `FluxLift`, ...).

Namely, it silently hides the original `Publisher` under a `Scannable.UNAVAILABLE_SCAN` if it isn't by itself `Scannable`, due to `Scannable.from(p)`.

There are still operators that have their base class non-`Scannable`, although these should probably be updated to be scannable.

Nonetheless, there are valid cases where the filter and/or the function could be applied without the `Publisher` being `Scannable`, so maybe a `BiPredicate<Scannable, Publisher>` and a `BiFunction<Scannable, Publisher<I>, Publisher<O>>` would make more sense.

### PR DESCRIPTION
**Pull request by simonbasle**
@smaldini here is a first attempt at improving the lift contract, providing a basis for discussion to #1105.

### CODE REVIEW

**Comment by smaldini** [comment]
I'm slightly reserved on that change and would prefer to address the Scannable issue directly:
- Publisher is always subscribed anyway after the call from a hook or transform perspective
- Publisher only offers subscribe()
- In general API could segregate the Publisher consuming from their top level API, e.g. in netty we would use receive() : Flux and that wouldn't give much information on the actual NettyInbound.
- Scannable could return a reference to the Publisher via introspection and attribute
- Scannable could offer a "optimizations()" or attr(Fusion) : int or the like than can easily have a default implementation

**Comment by simonbasle** [comment]
The problem is that some of these `Publishers` (even FluxXXX ones) are not `Scannable`, which makes the `BiFunction` and `Predicate` consume something _that has no reference to the original `Publisher`_, and (in the case of eg. Sleuth) making bad decisions based on this.

 - > Publisher is always subscribed anyway after the call from a hook or transform perspective
   - and that's fine. we don't want to prevent subscribe (which is the job of the filter) but rather create the subscription based on additional criterias **with a guarantee that we see the original `Publisher`.
 - > Publisher only offers subscribe()
   - again, not a matter of what you can do with the `Publisher` but what you can learn from it. You always have the option to attempt to convert it to `Scannable` for more introspection (but the reverse is not true).
 - > In general API could segregate the Publisher consuming from their top level API, e.g. in netty we would use receive() : Flux and that wouldn't give much information on the actual NettyInbound.
   - that wouldn't change anything with a `Scannable`, which would be `Scannable.from(receive())`.
 - > Scannable could return a reference to the Publisher via introspection and attribute
   - not if the original `Publisher` is not `Scannable` (we need the UNAVAILABLE_SCAN constant)
 - > Scannable could offer a "optimizations()" or attr(Fusion) : int or the like than can easily have a default implementation
   - right value for the default would be to assume `false`, which would not help in the Sleuth case, but that could be an interesting separate idea to expose the fusion mode

**Comment by smaldini** [comment]
Instead of passing Publisher then maybe Object (reference) would be better. Regarding Scannable we could specifically for Publisher keep a reference instead of only doing doing unavailable_scan we can add a reference attribute.  Can you link Sleuth original issue to see how to better address it. Lift is specifically to transform via a delegate chain the subscribing input to a subscribing output, at first the contract was passing a Publisher when I started testing with sleuth and micrometer before realizing that i was ever wanting to query the nature of the flow  (name, tags, and others).

**Comment by simonbasle** [comment]
@smaldini spring-cloud/spring-cloud-sleuth#646

What do you mean a `Scannable` with a reference attribute? A special implementation of `Scannable` that delegates if `p` is `Scannable` itself, with an additional `getter` for the original `Publisher`?

So usage would involve boilerplate like checking if the `wrapper.isScanAvailable()` and if not, perform checks on `wrapper.getPublisher()`. How is it cleaner and leaner than just providing the `Publisher`: the user would still have the full option of calling `Scannable.from(p)` himself, which is not worse in terms of boilerplate (IMO it is better)?

I don't see the rationale for `Object` either in this context.

`Publisher` sound like the perfect type to expose: it's the original type being hooked in, one can safely call any validation on it directly, including `instanceof`, and also pretty quickly transform it to a `Scannable` if relevant, with the caveat that it could just return `UNAVAILABLE_SCAN`. But at this point, the API doesn't trick the user into thinking it is always Scannable and that it is ok to do their `instanceof` on that `Scannable`.

**Comment by simonbasle** [comment]
opened a new PR for `Scannable` coverage. Will graft the javadoc improvements on top of it.

**Comment by smaldini** [comment]
Feel free to close this PR. We can open another issue to elude whether to bring in or not an extra method "Object reference()"  that would default to this for Scannable implementor, and for wrapped objects like publisher, the original publisher.

**Pull request closed without merging**
