### PR TITLE
Add #1123 metrics to `Flux`

### PR DESCRIPTION
**Pull request by simonbasle**
work in progress first MVP

### CODE REVIEW

**Comment by smaldini** [comment]
Given how frequent or transverse this could be, we should add microfusion support as well.

**Comment by smaldini** [comment]
Should metrics for Schedulers be in a separate PR ?

**Comment by simonbasle** [comment]
> Should metrics for Schedulers be in a separate PR ?

Yes I think it would make sense to consider this a MVP and fine tune meters and/or add instrumentation of schedulers in another PR

**Comment by simonbasle** [comment]
TODO: make the `Metrics` class package-private (we don't expect most people to interact with meters programmatically, so they won't really need the constants)

**Pull request merged**
