### PR TITLE
Add ScriptedSubscriber

### PR DESCRIPTION
**Pull request by poutsma**
This commit introduces a new Subscriber implementation meant for testing
purposes: the ScriptedSubscriber. This subscriber is set up with signal
expectations before subscribing. Expectations will be verified with a
verification step, resulting in an AssertionError if they are not met.

### CODE REVIEW

**Comment by nebhale** [comment]
@poutsma I've started doing some testing against our code and things look really nice.  Compared to our implementation, we're missing two operations (so far).

The first is `.expectCount(int)`.  This can be more or less replicated with `expectValues()` with actual values, but in our case, the types we'd have to replicate far enough to ensure that `.equals()` works are quite involved.  What used to be a single line `.expectCount(3)` is now 50 lines of object setup.

The second is an `.expectError(Class, String, Object...)` which matches on the message as well.  I'm not so sure that one should make the cut, or should be a `Predicate` that we have hanging around instead.  Interested in your thoughts there.

**Comment by nebhale** [comment]
Another thing that comes to mind is that there's no way to control the message that is emitted in the case of failure.  If I wrote a custom `Predicate` there's no way for me to communicate exactly what about that predicate caused the failure.

**Comment by poutsma** [comment]
@nebhale: thanks for your feedback!

> The first is .expectCount(int)...

Did you see the static `ScriptedSubscriber.expectValueCount(long)` method? I think that's what you were looking for. You can use that instead of `create` to build a subscriber that counts values, as opposed to individually expecting them. The reason for the separate static method is that when using `expectValueCount`, the DSL doesn't allow you to add `expectValue` calls, as they do not make any sense in that context. In other words: you can do `expectValueCount` or any of the `expectValue` variants, but not both.

> The second is an .expectError(Class, String, Object...) ...

I'm not a big fan of this method signature, to be honest. I can see the reason for not having a single String parameter there, because you want to make the (expensive) `String.format` call only to happen if a failure actually occurs. But I think that we can achieve the same by replacing the String and Object.. parameters can with a `Supplier<String>`. Which brings me to:

>Another thing that comes to mind is that there's no way to control the message that is emitted in the case of failure.

Yeah, I will add the following method to help with this:

```java
ScriptedSubscriber<T> expectErrorWith(Predicate<Throwable> predicate, Supplier<String> messageSupplier);
```
Would that work, also in the `.expectError(Class, String, Object...)` scenario?

**Comment by nebhale** [comment]
@poutsma Nope, totally missed the `.expectValueCount()`.  It may be worth adding it to the `ScriptedSubscriber` class-level Javadoc.  That being said, it'll do exactly what I'd like and in a much safer way that I did it with the Java Client `TestSubscriber`.

Yep, `Function<T, String>` should be just fine.  I could get away with the `String.format` because I was testing a discrete thing (the message).  But with a `Predicate` which makes the test much more general, a more general failure message generator would be required.

I'll pop both of those changes in today when I hit the office, but both look good.

**Comment by nebhale** [comment]
@poutsma Another datapoint, not necessarily a requirement.  To work with the `.expectErrorWith(Predicate<Throwable>, Function<Throwable, String>)` behavior, I've created a class that encapsulates the logic I need.

```java
ErrorExpectation errorExpectation = new ErrorExpectation(IllegalStateException.class, "MISSING_ORGANIZATION_ID");

return ScriptedSubscriber.<SpaceQuota>create()
    .expectErrorWith(errorExpectation.predicate(), errorExpectation.assertionMessage());
```

Specifically, it has the following methods on it:

```java
public Function<Throwable, String> assertionMessage() {
    return t -> {
        if (!this.type.isInstance(t)) {
            return String.format("expected error of type: %s; actual type: %s",
                this.type.getSimpleName(), t.getClass().getSimpleName());
        }

        if (!this.message.equals(t.getMessage())) {
            return String.format("expected message: %s; actual message: %s", this.message, t.getMessage());
        }

        throw new IllegalStateException("Cannot generate assertion message for matching error");
    };
}

public Predicate<Throwable> predicate() {
    return t -> this.type.isInstance(t) && this.message.equals(t.getMessage());
}
```

What strikes me about this is that I've got more or less duplicated logic between the predicate and the assertion message.  In the [Java Client's `TestSubscriber`](https://github.com/cloudfoundry/cf-java-client/blob/f423d22764dd51626be6672d0a6bfba24ab693a8/cloudfoundry-util/src/main/java/org/cloudfoundry/util/test/TestSubscriber.java#L82-L85) we don't have this duplication because we've use JUnit's assertions to both test and generate messages.  It's seems clear to me that the tradeoff to use `Predicate<Throwable>` is what causes this duplication; we get the ability to catch multiple failures but it means that we have to run some of the logic twice.

**Comment by nebhale** [comment]
@poutsma Credit where it's due as well.  The required terminal operations is really good.  Happy to admin that my version was lacking these and they a really good touch.

**Comment by poutsma** [comment]
I could change the `expectErrorWithPredicate<Throwable>, Function<Throwable, String>)` to `expectErrorWith(Function<Throwable, Optional<String>>`, or even `consumeErrorWith(Consumer<Throwable>)`. Would that help? The only problem I would have with these variants is that, from a usability perspective, it's a less clear what to do than having a predicate. Especially  with the consumer-based variant.

Thoughts, @smaldini ?

**Comment by nebhale** [comment]
@poutsma This is why I hesitate to call it a requirement; I agree with you that it's much less clear what you want to do.  In the end, I'm creating a compound predicate which necessitates compound logic in the message phase.  And heck, I'm not even sure it _neccesitates_ it (I could just print a message that was both type and message for expected and actual on any failure, and let the user do a visual analysis).

One apparent difference that leads to this is that the `ScriptedSuibscriber` is designed so that it is the only thing that generates an `AssertionError`.  In the Java Client `TestSubscriber` we expected that users could make their own assertions (with JUnit or AssertJ) generating `AssertionError`s with the directly related messages.  Maybe there's something in that?

At any rate, we've got a pattern and we're fine for now, so I wouldn't make any changes (for this particular issue) wihtout another data point from a different team.  Our compound test might just be an outlier which you don't need to optimize for.

**Comment by simonbasle** [comment]
The `ScriptedSubscriber` part has been ported to reactor-tests (see reactor/reactor-addons#11).
The `Signal` part has been committed separately in 2741e1f

**Comment by bclozel** [comment]
I'm currently working on [SPR-14800](https://jira.spring.io/browse/SPR-14800), I'd like to share my experience so far.

The builder style, guided, API is really nice to use; I'm not worried anymore about asserting the state of the stream (no error? complete? both?). It's also expressing clearly that we subscribe to the publisher and that we need to verify our assertions.
Developers may forget to add the final `subscriber.verify()` statement and I think the test would silently "work", but again you should never trust a test that you've never seen fail.

The `expectValueWith(Predicate)` variant feels simple for many use cases, when a predicate failure is quite easy to track down. But for more complex types, I'd say that the `expectValueWith(Predicate, Function<T, String>)` may not be enough.

When testing a `Flux<DataBuffer>`, one can use:

```java
ScriptedSubscriber<DataBuffer> subscriber = ScriptedSubscriber
  .<DataBuffer>create()
  .expectValueWith(
    dataBuffer -> {
      // consume the DataBuffer and turn it into a String
      return "expected value".equals(bufferAsString);
    },
    dataBuffer -> {
      // can't consume the buffer as it's been consumed/released already
      return "expected '" + "expected value" + "', was '" + bufferAsString + "'";
    }
  )
  .expectComplete();
```

I'm probably missing something here, but currently I think that:
* the assertion and the error message creation should not be separated, it makes is really hard to easily create fine assertions and useful messages in separate places
* because they're separated, it's also harder to manage the lifecycle of the emitted signal; just like `DataBuffer`, we need to know if it's been consumed already and we may even be stuck if it's been recycled already
* there's no way to use an assertion library (e.g. hamcrest, assertj) and have to write custom ones
* maybe I'm just missing variants like `consumeValueWith(Consumer<T>)` and `consumeValuesWith(Consumer<T>...)`

**Comment by nebhale** [comment]
@bclozel You've hit upon exactly the same concern [I had](https://github.com/reactor/reactor-core/pull/201#issuecomment-251728394).  My strategy for dealing with the issue has evolved a bit, but fundamentally, fine grained testing an messaging on a single return value is problematic.  As an example, some code that I had previously:

```
.subscribe(this.testSubscriber
    .expectThat(consumer((domainId, spaceId, entity) -> {
        assertEquals(domainId, entity.getDomainId());
        assertEquals(spaceId, entity.getSpaceId());
    })));
```

now looks like:

```
Function<Tuple3<String, String, RouteEntity>, Optional<String>> assertion = function((domainId, spaceId, entity) -> {
    if (!domainId.equals(entity.getDomainId())) {
        return Optional.of(String.format("expected domain id: %s; actual domain id: %s", domainId, entity.getDomainId()));
    }

    if (!spaceId.equals(entity.getSpaceId())) {
        return Optional.of(String.format("expected space id: %s; actual space id: %s", spaceId, entity.getSpaceId()));
    }

    return Optional.empty();
});

ScriptedSubscriber.<Tuple3<String, String, RouteEntity>> subscriber = ScriptedSubscriber.<Tuple3<String, String, RouteEntity>>create()
    .expectValueWith(tuple -> !assertion.apply(tuple).isPresent(),
        tuple -> assertion.apply(tuple).orElseThrow(() -> new IllegalArgumentException("Cannot generate assertion message for matching entity")))
    .expectComplete();

...

.subscribe(subscriber);
```

Even this doesn't take into account the concern you had about one-time use items.

**Comment by poutsma** [comment]
I've added consumer-based variants, and removed the <Predicate, Function>-based variants. See https://github.com/reactor/reactor-addons/pull/12

**Comment by bclozel** [comment]
See reactor/reactor-addons#12

**Pull request closed without merging**
