### PR TITLE
Add predicate to bufferTimeout

### PR DESCRIPTION
**Pull request by gindex**
This PR provides possible implementation of bufferTimeout with predicate (see #1843)

### CODE REVIEW

**Comment by simonbasle** [comment]
hey @gindex just a heads up that since the 3.3.0 GA release is now scheduled for thursday sept. 19, I don't think we'll have time to review and integrate this PR. Since it is probably going to be exposed as a new operator, it should be possible to get in the next release instead.

**Comment by gindex** [comment]
@simonbasle I see, sure 👍 I am looking forward for suggestions and feedback on the PR

**Comment by simonbasle** [comment]
@gindex this is still a draft, is it ready for review? any further work you intended to do?

**Comment by gindex** [comment]
@simonbasle from requested functionality perspective, its done. Only Javadoc is missing, but I would prefer to add it, if the general approach is fine so far. 

Regarding the approach:
1. As @simonbasle mentioned above, as an alternative to the current solution, we could add a new operator instead of extending `FluxBufferTimeout`. 
2. The draft extends 4 existing `bufferTimeout` and adds 4 additional combining exiting ones with predicate. Here is the question, what's reasonable form the api perspective. 
3. `FluxBufferPredicate` has 3 modes `UNTIL, UNTIL_CUT_BEFORE, WHILE`. The current draft works only in `UNTIL` mode. Here is the question, if we need to support all of them. It would increase the `buffer*` surface additionally. 

In two weeks I will have more spare time, to work on that (if needed 😉).

**Pull request closed without merging**
