### PR TITLE
Fix buffer ctor error message displaying wrong variable name

### PR DESCRIPTION
**Pull request by underbell**
skip value error message showing size value
Change size variable to skip variable

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@underbell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2658)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2658) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@underbell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2658)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2658) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Review by OlegDokuka — APPROVED** [review]
LGTM

**Comment by pivotal-issuemaster** [comment]
@underbell Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2658)!

**Review by simonbasle — APPROVED** [review]
thanks for the submission, and for signing the CLA 👍

**Pull request merged**
