### PR TITLE
Clarify how to use processExistingClasses in debugging.adoc

### PR DESCRIPTION
**Pull request by kicmeri**
Proposing the change as I was unable to make it work in test method or with `@BeforeAll`. Hoping it may save time for others.

### CODE REVIEW

**Comment by simonbasle** [comment]
@kicmeri can you clarify what didn't work for you and what kind of error you got?

`processExistingClasses()` is supposed to help with instrumenting classes that have already been loaded, but IIRC not all JVMs support it.

the fact that you had to use a `static { }` initializer block migh hint that it works thanks to setting up the instrumentation earlier rather than thanks to the `processExistingClasses()` 🤔

**Comment by kicmeri** [comment]
@simonbasle I was trying to follow the documentation of reactor.
What I tried with JUnit5 in IntelliJIdea: 
```
    @Test
    public void should_prodDebug() {
        ReactorDebugAgent.init();
        ReactorDebugAgent.processExistingClasses();

        var source = Flux.range(1, 5)
                .single()
                .log();

        StepVerifier.create(source)
                .verifyError();
    }
```
This produced the exception, but without traceback as I'd have expected - just stacktrace. The introspection still seemed to have been applied (when run in debug mode).
```
14:43:54.618 [main] ERROR reactor.Mono.Single.1 - onError(java.lang.IndexOutOfBoundsException: Source emitted more than one item)
14:43:54.622 [main] ERROR reactor.Mono.Single.1 - 
java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:134)
...
```

I also tried with
```
@BeforeAll
static void setup() {
      ReactorDebugAgent.init();
      ReactorDebugAgent.processExistingClasses();
}
```
but with same result.

Then I came about [ReactorDebugAgentTest](https://github.com/reactor/reactor-core/blob/178e0c7cf799122afdd6bf89be32975d2b433609/reactor-tools/src/test/java/reactor/tools/agent/ReactorDebugAgentTest.java) that uses the `static` initializer block - only with that I've seen the traceback in unit test with `ReactorDebugAgent`.
```
14:47:10.551 [main] ERROR reactor.Mono.OnAssembly.1 - | onError(java.lang.IndexOutOfBoundsException: Source emitted more than one item)
14:47:10.554 [main] ERROR reactor.Mono.OnAssembly.1 - 
java.lang.IndexOutOfBoundsException: Source emitted more than one item
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:134)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoSingle] :
	reactor.core.publisher.Flux.single
	SampleTest.should_prodDebug(SampleTest.java:613)
Error has been observed at the following site(s):
	*__Flux.single ⇢ at SampleTest.should_prodDebug(SampleTest.java:613)
Original Stack Trace:
		at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:134)
...
```
Still, it can be that I'm just doing something wrong.

**Comment by simonbasle** [comment]
thanks for the clarifications, that's good feedback.
I wonder if it would work with a `TestExecutionListener` 🤔

this section of the documentation isn't intended as a recipe for unit tests specifically, but more as an indicator that the tool offers a path to JVM's [`Instrumentation.retransformClasses`](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/Instrumentation.html#retransformClasses(java.lang.Class...)) where it makes sense

**Comment by kicmeri** [comment]
@simonbasle The setup with `TestExecutionListener` works for me too producing the traceback.

Nonetheless, all I intended is to improve the doc. I see it is questionable whether it is really an improvement. Thus, when you say
> the documentation isn't intended as a recipe for unit tests specifically

feel free to close this PR.

**Review by simonbasle — CHANGES_REQUESTED** [review]
I think even though this wasn't intended as an example, it did confuse you.

We can probably add the `TestExecutionListener` example. The sentence before the snippet would need a bit of splitting and rewording. What do you think about:

```
You may also re-process existing classes with `processExistingClasses()` if you cannot run the init eagerly.
For example, in a JUnit5 `TestExecutionListener`:
```
then the modified sample (not static block but listener)

**Comment by kicmeri** [comment]
@simonbasle Well, thinking about it: My purpose was not exactly to use the PROD debugging feature _in test_. I just _tried it_ in the test. When I do it from regular application in my setup
```
public class ProdDebugApp {
    public static void main(String... args) {
        ReactorDebugAgent.init();
        ReactorDebugAgent.processExistingClasses();

        var source = Flux.range(1, 5)
                .single()
                .log();

        StepVerifier.create(source)
                .verifyError();
    }
}
```
I still get the no traceback. with the above code it again works only with static initializer, no JUnit framework involved at all.

Thus the wording pointing to unit testing is rather misleading and I'd prefer some hint on what to try, when the misbehaviour happens, regardless of the cause.

**Review by simonbasle — APPROVED** [review]

**Comment by simonbasle** [comment]
yeah I think that works 👍

**Comment by simonbasle** [comment]
I'll rebase this PR on top of `3.4.x`, which should also trigger a new run of CI, then will merge 👍

**Pull request merged**
