### PR TITLE
fix #616 Keep one significant factory method for Processors with Builder

### LINKED ISSUE #616: Follow-up to processor builders, keep key static factories
As a follow up to #471 / #610, we might want to consider keeping a few essential factory methods un-deprecated. Focus on the ones that are likely to be the most heavily used (see internal operators usage for instance), in order to avoid the overhead of the builder in these cases.

### PR DESCRIPTION
**Pull request by simonbasle**
This commit removes the recent deprecation on a few factory methods for
Processors that now have a Builder, keeping most significant and short
constructions from the boilerplate of using a builder.

WorkQueueProcessor and TopicProcessor keep the create/share with name
and bufferSize, UnicastProcessor keeps the queue+terminationCallback
variant and EmitterProcessor keeps the bufferSize variant.

### CODE REVIEW

**Comment by simonbasle** [comment]
@smaldini rebased on latest master 😃 
This contains also improvements to the javadoc, but basically the un-deprecated factory methods are described in the commit msg:

> WorkQueueProcessor and TopicProcessor keep the create/share with name
and bufferSize, UnicastProcessor keeps the queue+terminationCallback
variant and EmitterProcessor keeps the bufferSize variant.

marked as `pending-confirm-resolved` and assigned to you so you can approve or reject the choice of un-deprecated factory methods.

**Comment by smaldini** [comment]
I don't see UnicastProcessor fixed tho, 
https://github.com/reactor/reactor-core/blob/f24cdee0d2344b21965ec1add5bc45baa4418e90/reactor-core/src/main/java/reactor/core/publisher/UnicastProcessor.java#L174 still uses a builder to create itself (it shouldn't have).

**Comment by simonbasle** [comment]
@smaldini what do you mean? The goal of this PR is to avoid removing ALL factory methods, but still favor the builder and **only keep one or two factory methods**, aka the most used ones. The method you highlighted is one of the still deprecated ones, which will be removed.

Did you mean you think this `UnicastProcessor#create(Queue<E> queue, Consumer<? super E> onOverflow, Disposable endcallback)` factory method is the most used and should be un-deprecated?

**Comment by simonbasle** [comment]
See update to issue, we'll keep **all** factory methods on `EmitterProcessor` and `UnicastProcessor`.

**Comment by smaldini** [comment]
To remove: builder in unicast and emitter

**Pull request merged**
