### PR TITLE
fix #947 doOnEach with context

### LINKED ISSUE #947: Support for simpler use of Context on different signals
Ideally should be able to do simple operations using context on next/error signals such as set/reset current thread context classloader or maybe set a ThreadLocal for some legacy code.

Currently, this can be done fairly easily for `onNext` signals, but in cases where there is no need to do anything with the event, it preferred if it was possible to use the current context in `doOnNext` or `doOnEach`.

For error signals, on the other hand, there is currently no way, that I could find, to do something simple using the current context on error signals.

It may not make sense to have a context-aware version of all onX methods, but by having a `doOnEach` version that receives the current context at least these use case could be achieved easily.

Currently, need to do something like this:

```
.transform(doOnNextOrErrorWithContext(context -> context.getOrEmpty(TCCL_REACTOR_CTX_KEY).ifPresent(cl -> currentThread().setContextClassLoader((ClassLoader) cl))))
.transform(next)
.transform(doOnNextOrErrorWithContext(context -> context.getOrEmpty(TCCL_ORIGINAL_REACTOR_CTX_KEY).ifPresent(cl -> currentThread().setContextClassLoader((ClassLoader) cl)))));


  private Function<? super Publisher<CoreEvent>, ? extends Publisher<CoreEvent>> doOnNextOrErrorWithContext(Consumer<Context> contextConsumer) {
    return lift((scannable, subscriber) -> new CoreSubscriber<CoreEvent>() {

      private Context context = subscriber.currentContext();

      @Override
      public void onNext(CoreEvent event) {
        contextConsumer.accept(context);
        subscriber.onNext(event);
      }
      @Override
      public void onError(Throwable throwable) {
        contextConsumer.accept(context);
        subscriber.onError(throwable);
      }

      @Override
      public void onComplete() {
        subscriber.onComplete();
      }

      @Override
      public Context currentContext() {
        return context;
      }

      @Override
      public void onSubscribe(Subscription s) {
        subscriber.onSubscribe(s);
      }
    });
  }
```

But should really be able to do something like this:
```
.doOnEachWithContext((s, context) -> {
    context.getOrEmpty(TCCL_REACTOR_CTX_KEY).ifPresent(cl -> currentThread().setContextClassLoader((ClassLoader) cl))))
}
.transform(next)
.doOnEachWithContext((s, context) -> {
    context.getOrEmpty(TCCL_REACTOR_CTX_KEY).ifPresent(cl -> currentThread().setContextClassLoader((ClassLoader) cl))))
}
```

### PR DESCRIPTION
**Pull request by simonbasle**
~This is still work in progress~
issue: #947

### CODE REVIEW

**Comment by smaldini** [comment]
I'm not entirely convinced by the extra API, we could use an alias to materialize eventually and pass currentContext() : 
```materialize(BiConsumer<Signal, Context>)``` . I still find the overall requirement niche so far as it requires a mutable context value to be effectively useful.

**Comment by simonbasle** [comment]
@smaldini the idea is to be able to perform some action that reads from the `Context`, on `onNext` or `onError` signals. There is no aim at mutating the `Context`.

> For error signals, on the other hand, there is currently no way, that I could find, to do something simple using the current context on error signals.
> 
> It may not make sense to have a context-aware version of all onX methods, but by having a doOnEach version that receives the current context at least these use case could be achieved easily.

I didn't want to integrate the notion of `Context` in the `Signal` interface, as it doesn't necessarily make sense in all cases where we provide or get a `Signal`, hence the new `SignalWithContext` API. Apart from that, no new method or public class is added (the current `doOnEach` is augmented to receive a `SignalWithContext` but should be backward-compatible with pre-existing `Consumer<Signal>`).

I'm not a fan of the `materialize` overload, which would return a `Flux<Signal>` that we don't need.

The only other option I see is a new `doOnEachWithContext()` that would take a `BiConsumer<Signal, Context>`.

**Comment by dfeist** [comment]
@smaldini Agree 100% with @simonbasle. Did you see the use case in the github issue and the only that there is currently to use the context for this?

**Comment by smaldini** [comment]
What about doWithContext

**Comment by simonbasle** [comment]
@dfeist changed toward a separate operator (`doWithContext`) that takes a `BiConsumer<Signal, Context>`.

**Comment by dfeist** [comment]
@simonbasle ok, I never had a strong opinion either way anyway as long as use case is supported. The only thing with the new name is the fact that it's a `onEach` operator that receives a `Signal` is implied rather than explicit.  That said, `doOnEachWithContext` is a bit of a mouthful!

**Comment by simonbasle** [comment]
squashed in anticipation of a rebase-merge, but the background discussion around naming tends to favor `doOnEachWithContext` (consistent and explicit rather than concise naming).

**Comment by smaldini** [comment]
I think doOnEach should be fine even if it overloads the existing doOnEach, I wonder if we should just go this way for 3.2 and provide an extra kotlin annotation meanwhile ?

**Comment by dfeist** [comment]
@smaldini Personally I thought the best option was just to add context to signal and use `doOnEach` as it is today. `handle` exposes context via an extra method on `Sink` and there isn't a `handleWithContext` of anything.  But for some reason, you didn't like that approach. 

IMO it's best to add context to Signal/Sink which can optionally be used when using handle/doOnEach etc. than to increase the surface area of the Flux API itself.  For those who want to use context with those operators it's there for them, with no need to use a different operator, and for those that don't want to use it, well they aren't negatively impacted and don't waste time wondering if they should use Flux.doOnEach or Flux.doOnEachWithContext.  There is also consistency with `handle` which already exposes context without its own method.

**Comment by smaldini** [comment]
@dfeist I leaned towards your idea too, Signal could have a currentContext() method, the problem is with materialize() which will cost a bit more if we implement context as well. I think a Signal with a Context makes sense giving the full "contextual" information given a signal.

**Comment by simonbasle** [comment]
It also means Signal can't be lightweight/reusing singletons in the case of complete, although that's pretty narrow

**Comment by smaldini** [comment]
@simonbasle in the case of onEach its fine since the operator itself implement the Signal as a singleton. For materialize yes that would cost a new allocation for complete.

**Comment by simonbasle** [comment]
@smaldini yes; I'm more concerned about the extra field on onNext Signals, that said. these have the potential to be created a lot

**Pull request closed without merging**
