### PR TITLE
[docs] Fix bad blocks in refguide causing formatting errors

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @Buzzardo FYI adding these "example" blocks (`====`) around source blocks (`----`) broke the rendering quite a bit

**Comment by Buzzardo** [comment]
How did it break?

**Comment by simonbasle** [comment]
Some paragraphs would be rendered as snippets (including titles), a whole appendix even disappeared (appendix C)...

**Comment by Buzzardo** [comment]
That's a result of one being missing (unbalanced). I'll work on it again.

**Comment by simonbasle** [comment]
@Buzzardo do you strongly feel these `====` wrapping blocks are needed? what do they bring?

The syntax for source code with title and syntax highlighting is documented in "Code block with title and syntax highlighting" section of [source code syntax](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code) as:
```
.title
[source,java]
----
int someSource = 3;
---
```

**Comment by Buzzardo** [comment]
They keep the code callouts together with the code. Then, because we use them in those places, we have to use them everywhere to get the appearance to be consistent.

**Pull request merged**
