### PR TITLE
ConditionalSubscriber support where it is missed

### PR DESCRIPTION
**Pull request by OlegDokuka**
This PR provides [`ConditionalSubscriber`](https://github.com/reactor/reactor-core/blob/628258f644bdddd095e72d1fc81c5d6ac0e3fa12/reactor-core/src/main/java/reactor/core/Fuseable.java#L60) fusion support in common operator:

- [x] FluxSubscribeOn
- [ ] FluxSkip
- [ ] FluxRepeat
- [ ] FluxRepeatPredicate
- [ ] FluxRetry
- [ ] FluxRetryPredicate
- [ ] FluxMetrics

Signed-off-by: Oleh Dokuka <shadowgun@i.ua>

### CODE REVIEW

**Comment by OlegDokuka** [comment]
Would love to hear any suggestions/objections/comments before I push the rest of the operators (FYI, they are prepared without tests, found those missing gaps during verification of FluxLimitRate operators, so decided to implement them)

cc/
@simonbasle 
@bsideup

**Comment by simonbasle** [comment]
I was wondering about how we duplicate code a lot between conditional variants and normal variants. The caveat of making the conditional one extend the normal one, on the other hand, is that it can deepen the stacktraces. A good middle ground would be to split the subscribers into an abstract base and 2 concrete final implementations, where each method that needs to be implemented in a particular way in either class would be made abstract (or omitted) in the base class. Does that sound about right @smaldini ?

**Comment by akarnokd** [comment]
Since it is needed to wrap arbitrary `org.reactivestreams.Subscriber` anyway, maybe the conditional could be the default internal API, so there is no need to typecheck every consumer.

**Comment by OlegDokuka** [comment]
I'm with you @simonbasle @akarnokd it is just my pain finding such things, so I'm more than happy to fix that whiles I have some spare time to do that.

@akarnokd A drawback of using the conditional as a default co-implementation (I hope I understood you correctly) is a couple of `if` instructions but I'm not sure how painful it is compared to type check.

I was thinking about something like a generic base class, e.g. -> https://gist.github.com/OlegDokuka/9516f3e13dd8ea13bbf8afee85afd6fd

**Comment by simonbasle** [comment]
do you still feel the need to make progress on this one @OlegDokuka ?

**Comment by OlegDokuka** [comment]
@simonbasle, I'm open to finish that if we all think that is a needed improvement! As usual, you may count on my contribution 😁

**Comment by chemicL** [comment]
The last interaction here was over 4 years ago. Closing due to inactivity. Please create a new PR targeting the latest codebase in case you feel this is still applicable.

**Pull request closed without merging**
