### PR TITLE
fix #580 Example of callback hell vs reactor in refguide

### LINKED ISSUE #580: Add Examples to "Asynchronicity to the rescue?"
I think it would be valuable if the documentation provided examples that illustrate the points made in the [Asynchronicity to the rescue?](http://projectreactor.io/docs/core/release/reference/docs/index.html#_asynchronicity_to_the_rescue). An example of using each of the Reactor alternatives and then how Reactor cleans this up would really speak volumes.

### PR DESCRIPTION
**Pull request by simonbasle**
cc @rwinch, covered callbacks at least. do you think a `Future` example is absolutely needed for #580 ?

### CODE REVIEW

**Comment by rwinch** [comment]
Thanks for the fast turnaround on this! 

I'd argue that neither are absolutely needed, but each example makes the statements made in the reference stronger. For that reason, I'd be inclined to add a sample for `Future`.

If you find the samples are too much of an interruption to the reader, perhaps the samples could be added to the appendix and then linked to from this section?

**Comment by simonbasle** [comment]
For rendering, see:
[reactor-core-reference-guide-3.1.0.BUILD-SNAPSHOT.pdf](https://github.com/reactor/reactor-core/files/989498/reactor-core-reference-guide-3.1.0.BUILD-SNAPSHOT.pdf)

**Comment by smaldini** [comment]
It's heroic stuff IMO

**Comment by rwinch** [comment]
@simonbasle 

> I fear this might be too much of an interruption though, especially since we haven't introduced Reactor, the Flux and Mono types nor the concept of operators...

While the reader might not understand it all, it is easy to see an improvement. Providing a before / after gets the reader hooked to motivate them to continue reading the document and provides a reason to not use another framework.

**Pull request merged**
