### PR TITLE
Add Flux.fromPaginated operator to expand paginated objects

### PR DESCRIPTION
**Pull request by simonbasle**
This is intended to address #1998 but is better than a generic expand-based solution (as expand enforces same type for source objects and expanded objects).

TODO:
  - [x] test scannable
 - [x] implement scanUnsafe for the publisher and the main
 - [x] add better state management in the main and allow detection of cancelled/terminated
 - [x] document the operator in "which operator do I need"
 - ~[ ] add more (stress?) tests?~
 - [x] find a better name
 - [x] marble diagram

### CODE REVIEW

**Comment by simonbasle** [comment]
Note: I had started looking into a state machine implementation, but it was way more complicated and I felt the `synchronized` blocks are a better solution, given that they synchronize on a very short region.

**Comment by simonbasle** [comment]
We're still evaluating the benefit of this approach (and if you read this and think the API would solve an issue you have / improve your situation, please say hi 😄).

**Comment by simonbasle** [comment]
It would seem that the fetching of the content being a `Publisher` isn't terribly useful.
Even in consuming REST apis where the next page URL is defined in the headers, the content of a given page is still readily available in the body (and in the case of WebFlux, you cannot really defer subscribing to the body `Flux`).

So taking that into consideration, this approach has only one little advantage over the `expand/expandDeep` approach with `flatMapIterable`: it requests the exact number of pages needed.

`expand[Deep]` does fetch one more page than needed which gets cancelled (in the case of eg. a `limitRequest`).

in that "next page info is in the headers" type of request/API, there is some boilerplate in extracting the next link from the headers in both cases. There's also repetition in fetching the first page versus subsequent pages anyways, or one must resort to a trick of creating a "fake page" with a `nextLink` entry as a starting point, but in any case neither approaches particularly shine in that regard.

consider:

```java
static class GithubPage {

		final int                       page;
		final int                       per_page;
		final List<String>              links;
		final List<Map<String, Object>> content;
		final Optional<String>  nextLink;

		public GithubPage(int page, int per_page,
		                  List<String> links,
		                  List<Map<String, Object>> content) {
			this.page = page;
			this.per_page = per_page;
			this.links = links;
			this.content = content;

			this.nextLink = computeNextLink(links);
		}

		public GithubPage(int page, int per_page, String nextUrl) {
			this.page = page;
			this.per_page = per_page;
			this.links = Collections.emptyList();
			this.content = Collections.emptyList();
			this.nextLink = Optional.of(nextUrl);
		}

        public List<String> getContent() {
            return this.content;
        } 

		private static final Pattern LINK_PATTERN = Pattern.compile("<(.*)>; rel=\"(\\w*)\"");

		static Optional<String> computeNextLink(List<String> rawLinksList) {
			Map<String, String> parsedLinks = new HashMap<>();
			for (String rawLinks : rawLinksList) {
				for (String entry : rawLinks.split(",")) {
					Matcher matcher = LINK_PATTERN.matcher(entry.trim());
					if (matcher.matches() && matcher.groupCount() == 2) {
						parsedLinks.put(matcher.group(2), matcher.group(1));
					}
				}
			}
			String next = parsedLinks.get("next");
			return Optional.ofNullable(next);
		}

		@Override
		public String toString() {
			return "GithubPage{" +
					"page=" + page +
					", per_page=" + per_page +
					", content(" + content.size() + ")" +
					", nextLink=" + nextLink +
					", links=" + links +
					'}';
		}
	}
```
as well as this method to fetch a page:
```java

	private static final Logger LOG = LoggerFactory.getLogger(GithubController.class);

	static Mono<GithubPage> nextPage(GithubPage fromPage) {
		LOG.info("Fetching next page and its content from " + fromPage);
		return fromPage.nextLink
				.map(next -> WebClient.create(next)
						.get()
						.exchangeToMono(cr -> cr.bodyToFlux(Map.class)
								.map(m -> (Map<String, Object>) m)
								.collectList()
								.map(content -> new GithubPage(
										fromPage.page + 1, fromPage.per_page,
										cr.headers().header("Link"),
										content)
								)
						)
				).orElse(Mono.empty());
	}
```

In the case of candidate `fromPaginated`, to get a `Flux` of json objects (as Maps), usage would be something like:
```java
Flux.fromPaginated(
				new GithubPage(0, 3, "https://api.github.com/orgs/"+ organization + "/repos?per_page=3"),
                GithubPage::getContent //was Publisher, but we've concluded it doesn't bring much
				GithubController::nextPage
		)
```
With `expand` it would be something like:
```java
Flux<GithubPage> initPage = Flux.just(new GithubPage(0, 3, "https://api.github.com/orgs/" + organization + "/repos?per_page=3"));

Flux<GithubPage> expanded = initPage.expand(GithubController::nextPage)
    .flatMapIterable(GithubPage::getContent);
```

**Comment by simonbasle** [comment]
so far it doesn't look that much more useful. wondering if it could be applied to the case in https://github.com/reactor/reactor-core/issues/2154 though... I can have a look, but would appreciate any insight from @maxim-bandurko-lsvt

**Comment by simonbasle** [comment]
> so far it doesn't look that much more useful. wondering if it could be applied to the case in #2154 though... I can have a look, but would appreciate any insight from @maxim-bandurko-lsvt

not sure it would help very much with that other issue, since it deals with materializing downstream requests into "Pageable"...

that said, the exploration made in this PR would reverse the logic and fetch multiple pages if the request from downstream overflows the content of a single page.

**Comment by simonbasle** [comment]
a few further ideas:

 - restricting to `Iterable<T>` for the page content rather than a `Publisher`, we can optimize for the `Collection` case by knowing right away if the collection is smaller than the current downstream request.
 - the signature of the method could be further expanded to fix the clunkyness of having to create an artificial first page:

```java
public static <P, PID, T> Flux<T> fromPaginated(
		PID firstPageIdentifier,
		Function<? super PID, Mono<P>> pageFetchFunction,
		Function<? super P, ? extends Iterable<T>> pageStaticContentFunction,
		Function<? super P, PID> nextPageIdFunction) { }
```

The addition of the P -> PID function allows to have a unified way of fetching a page from its url, while differenciating between the first page case (we know the url) vs next page case (eg. we extracted the next url from the headers of the response and stored it in the `Page` object):

```java
String organization = "reactor";
Flux<Integer> unpaginated = Flux.fromPaginated(
	"https://api.github.com/orgs/"+ organization + "/repos?per_page=3",
	url -> client.fetchPage(url), //fetch page, extract next Url from headers. returns Mono.empty() if next url is null/empty
    page -> page.values,
	page -> page.nextPageUrl
);
```

**Comment by maxim-bandurko-lsvt** [comment]
@simonbasle case that I proposed at https://github.com/reactor/reactor-core/issues/2154 is much more agnostic and simpler, as it is basically modified "limitRate" that exposes calculations to function and allows to have any logic applied inside it. For example, here are use cases where I am using it: 
1. Custom R2DBC queries that should have "lazy" select/update/insert/delete (example, stats counter, that should insert a specific record based on already inserted records qty using the "offset" variable).
2. Elasticsearch queries with "searchAfter" use just a function with "limit" variable only and storing sorting keys values for next method call as a start point for next the elasticsearch searchAfter query (this way I implemented lazy pagination for searchAfter that works pretty good and not overloads server memory with huge prefetching data). Had more use cases that brought me to implement floating "limit" variable that is increasing/decreasing it's value based on frequency of method call (like prefetching 100 items on first call, after that 1k items on second or keeping same 100 if next call exceeded one hour).
3. WebClient that should use those 2 variables to construct urls. Similar to your implementation, but with no Pageable. Also had a use case that WebClient had several nested sub paginations, so it was very easy to implement sub and sub-sub paginations by reusing same method inside function and constructing complex nested sub urls for a WebClient.
4. Realtime data synchronization - basically same as a use case 2 with Elasticsearch, if client had requested more realtime data to consume, but his offset is very old, method just trigger a switch action to new Flux instance of those `limitRate` operator that has "fresh" offset variable.
... can continue listing more use cases if it is needed.

I came to such dependency-less proposal because Reactor Core should be agnostic and abstract, and just provide tools for implementation of other specific things that Spring packages may need. 

`Flux.fromPaginated` that you described I think is more specific and may have less use cases implementations. But if `PID` that you described can be a BiFunction with `offset` and `limit` - this will suite to all use cases that I have.

**Comment by simonbasle** [comment]
> `Flux.fromPaginated` that you described I think is more specific and may have less use cases implementations. But if `PID` that you described can be a BiFunction with `offset` and `limit` - this will suite to all use cases that I have.

The `Function<PAGE, PAGE_ID>` that I added in the last round could maybe be turned into `BiFunction<PAGE, Long, PAGE_ID>` where the `Long` is the amount of outstanding request, which could then be used as a hint for the next page's limit in case `PAGE_ID` type is something like an offset+limit in a db request.

At the same time, I'm worried this is a bit too niche of a case... Still thinking on this.

**Comment by maxim-bandurko-lsvt** [comment]
@simonbasle It is just how to look onto it's purpose... It looks to be not so popular in only WebFlux application, as everything connected with a http request and headers, but when it comes to RSocket (using Websocket or TCP servers with scenario of internal communications between servers) - those variables are very in need, as clients have persistent connections and servers have to deal with all those Flux requests that can have different flow all the time in order to save server resources by utilizing backpreasure and be "lazy" functional as much as possible.

Any way, it is up to you. When I did those my proposal I got to very need of those method and had to implement such operator into my framework (as there were no way out how to achieve that in more convenient way). May be with some time, RSocket become more popular and more developers will get to same issues that I had. But it would be nice, if that would be implemented inside Reactor Core directly (I am trying to avoid my custom overrides to Reactor and other packages in my  framework). 

I can list more use cases (mostly it will be ISC applications logics) if that can help to make final decision.

**Comment by maxim-bandurko-lsvt** [comment]
@simonbasle I think I need to update my proposal, as I am talking about not only Pageable constructor.
```
Flux.limitRate(
    (long offset, long limit) -> {
        return ............ some Flux .............;
    },
    100
)
```

**Comment by maxim-bandurko-lsvt** [comment]
@simonbasle Btw, here is raw example of your functionality:

```
Flux.limitRate(
    (long offset, long limit) -> {
        return new GithubPage(offset, limit, "https://api.github.com/orgs/"+ organization + "/repos?per_page=" + limit)
              .nextLink
				.map(next -> WebClient.create(next)
						.get()
						.exchangeToMono(cr -> cr.bodyToFlux(Map.class)
								.map(m -> (Map<String, Object>) m)
								.collectList()
								.map(content -> new GithubPage(
										fromPage.page + 1, fromPage.per_page,
										cr.headers().header("Link"),
										content)
								)
						)
				).orElse(Mono.empty());
    },
    100
)
```

**Comment by maxim-bandurko-lsvt** [comment]
@simonbasle I think may be need to provide some explanation on it. Once operator got to limit, it executes function again to get into a new Publisher. If new Publisher has nothing to publish, it has to return empty publisher (that is how publisher of operator will get into completed phase). If requester had canceled stream - all will be stopped and drained (publisher will be disposed).

With your requirement it was needed to do the first WebClient request as to get the initial qty (coming from.https://github.com/reactor/reactor-core/issues/1998 ) - this can actually be implemented inside those GitHub class functionality. And those class can just have a method, like `request(long offset, long limit)` that is going to do all needed logic and return publisher.

```
Flux.limitRate(
    githubPage::request,
    100
)
```

So, in publisher streams chaining all will be shortened and looking very nice in the end.

**Comment by simonbasle** [comment]
The `GithubPage` is a test-oriented class that simulates responses from the github API, where only the first request will have a `per_page` parameter. From there on, each response contains an URL that allows to fetch the next page. The URL isn't really intended to be re-generated from the offset/limit on each round.

I don't think most paginated APIs out there can deal well with a moving `offset` and `limit`, can they?
Which means that the `BiFunction` only makes sense for the initial request. In fact, at that point it can be removed altogether since that is equivalent to the `100` parameter (initial offset is 0, initial limit is the second parameter of your proposal).

Also, the `fromPaginated` idea was to expand each `PAGE` object into one or more elements of content (which again seem to be always part of the response in paginated APIs), so the resulting `Flux` is `Flux<CONTENT>`, not `Flux<PAGE>`.

What I found interesting while exploring `fromPaginated` was requests from downstream (which represent request of `<T>`) overflows over to the next page. If downstream requests 123, and page size is configured to be 100, then once first page has been "consumed" the operator would request a second page and deliver 23 elements from its content.

From the use cases that you exposed (which are still a bit fuzzy to me in terms of consumed APIs), it seems that the content of a page would benefit in some cases from being represented as a `Flux<T>` rather than `Iterable<T>`. That was the first direction I took, and switched to `Iterable<T>` because I didn't have a concrete case in mind where the "page" response wouldn't include the content / elements.

**Comment by maxim-bandurko-lsvt** [comment]
It very depends on use cases... I also think that `Flux<T>` will have more use-cases rather than `Iterable<T>`, as it will directly construct the stream data into the flow.

I thought that `GithubPage` was re-generating the urls. But, any way, not all restful services can have such logic, as mostly, all of them require at least page number for request. Even if we start looking onto different cloud services, like AWS, Google, Azure, etc, there will be a lot of situations, when it is needed to use "counter" of already consumed data in restful calls. Having `BiFunction` with `offset` and `limit` can make operator to be more abstract, flexible and be a multipurpose tool. When it comes to deal with real pagination, this operator can be used inside Spring framework utilities and do all need logic, or even be generated to new object that exposes variable with`Pageable` interface for future manipulations. 

In my practice, I have such list of most actively used candidates of such operator with exposed variables:

### 1. Databases
Spring Data allows very basic process of dealing with databases, that can suite in full with simple APIs. But in real life, SQL query can't be just CRUD generated, as mostly it has multiple joins that can be very complex, and uses plain text of it. At that moment, there are no easy way in Spring framework to make those query be pageable. Very basic and most common scenario example (above 80% of SQL in any API):
```
@Repository
public interface SomeDAORepository extends R2dbcRepository<SomeDAO, Long>, SomeDAORepositoryImplI{

	@Query("SELECT tableA.id AS id, tableA.name AS name, tableB.group AS group, tableC.status AS status FROM someTableA tableA LEFT JOIN someTableB tableB ON tableB.id = tableA.id AND tableB.dep IS NULL INNER JOIN someTableC tableC ON tableC.section = tableB.section AND tableA.group = tableC.group WHERE tableA.group = :group AND tableC.inq = 0 LIMIT :limit OFFSET :offset")
	public Flux<SomeDAO> findByGroup(long group, long offset,  long limit);

}


@NoRepositoryBean
interface SomeDAORepositoryImplI {

	public Flux<SomeDAO> findByGroup(long group);
        public Flux<SomeDAO> findByGroup(long group, long startAfter);

}


class SomeDAORepositoryImpl implements SomeDAORepositoryImplI {

	@Autowired
	private SomeDAORepository repository;
		
	public Flux<SomeDAO> findByGroup(long group){
        return Flux.fromBatched(
            (long offset, long limit) -> {
                return repository.findByGroup(group, offset, limit);
            }, 
            0,
            100
        );
	}


	public Flux<SomeDAO> findByGroup(long group, long startAfter){
        return Flux.fromBatched(
            (long offset, long limit) -> {
                return repository.findByGroup(group, offset, limit);
            }, 
            startAfter,
            100
        );
	}
	

}
```

With Elasticsearch database operator can be used in "searchAfter" scenario by utilizing only `limit` variable (as in Elasticsearch is needed to provide the exact value of sort indexes after what to start searching)

Using such operator in database allows to deal with huge datasets by not overloading databases and not having huge prefetch flow at server that consumes resources.


### 2. WebClient calls to restful APIs that requires pagination by providing `page` number or `offset` with `limit`.


### 3. RSocket persistent connections (WebSocket or TCP). Very often is needed to "re-stream" the RSocket connection in way that won't interrupt the client and continue correct data flow. In this situations having the `offset` helps to "get into the needed part from whole available data stream". Very basic example: infinity scroller that is requesting the certain amount of data to produce in stream based on scroll position at browser. Or inter services communication chains, when TCP connection was interrupted while stream chain between 2 servers was "hot", it is needed to make a proper "re-stream".

**Comment by simonbasle** [comment]
Closing this as there doesn't seem to be much traction nor benefit to it

**Pull request closed without merging**
