### PR TITLE
Rename Fuseable to Mergeable

### PR DESCRIPTION
**Pull request by sdeleuze**

### CODE REVIEW

**Comment by akarnokd** [comment]
Isn't Fuseable script generated from Rsc?

**Comment by smaldini** [comment]
Ignore this, I haven't yet been vocal around its purpose

**Comment by sdeleuze** [comment]
Indeed sorry, Stéphane gave me more info. So "merge" is not the right term. But if we are talking about "fusing", shouldn't `Fuseable` be renamed to `Fusable`in RSC ?

**Comment by akarnokd** [comment]
I'm not a native English speaker so I followed some earlier naming convention such as `java.io.Closeable` or `java.lang.Cloneable`.

**Comment by sdeleuze** [comment]
In english, `Closeable`and `Cloneable` are real english words. The only reference to `Fuseable` I found refers to a fusible, a wire that can break when too much intensity, that seems unrelated to fusing term used here.

Akka guys mentioned the term fusable is [this article](http://akka.io/news/2015/12/21/akka-streams-2.0-released.html) and in [their documentation](http://doc.akka.io/docs/akka-stream-and-http-experimental/2.0/AkkaStreamAndHTTPJava.pdf).

So I really thing `Fusable` is the right term.

**Comment by sdeleuze** [comment]
I reopen this PR for discussion since my proposal has changed, and I can create a PR on reactive-streams-commons if needed.

**Pull request closed without merging**
