### PR TITLE
Fix typo in Flux#single documentation

### PR DESCRIPTION
**Pull request by philleonard**

### CODE REVIEW

**Comment by simonbasle** [comment]
Thanks for the PR @philleonard ! Just in case you're motivated to look for more such typos, I can defer merging for a few more days since we're releasing end of week. Otherwise I can merge this directly, as you prefer.

**Comment by pivotal-issuemaster** [comment]
@philleonard Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1402)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1402) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@philleonard Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1402)!

**Comment by philleonard** [comment]
Caught some more low hanging fruit after a quick scan :)

**Comment by philleonard** [comment]
I think the build is failing due to a GC run request not being processed within 500ms on the JDK 9 build. My suspicions are that this relates to G1C1's concurrent requests? The default max pause time is 200ms, perhaps this can be reduced for the sake of a more stable build (`-XX:MaxGCPauseMillis=20`)? Will leave for a separate discussion.

**Comment by simonbasle** [comment]
@philleonard your GC tuning suggestion has been implemented as part of #1407

**Comment by philleonard** [comment]
👍 Nice, I hope It can improve the build stability.

**Pull request merged**
