### PR TITLE
Fix #513 by adding a new marble diagram

### LINKED ISSUE #513: Use a proper marble diagram for Flux.windowUntil
The marble diagram used for `Flux.windowUntil` doesn't really visualize what `windowUntil` does.

### PR DESCRIPTION
**Pull request by schauder**
A new marble diagram specific for `windowUntil` is used in the JavaDoc
for all variants of this method.

### CODE REVIEW

**Comment by simonbasle** [comment]
Nice! One small adjustment though: unless `cutBefore` is set to `true` (in the 2nd and 3rd variants), the green element which triggers the new window is emitted in the previous window.

So the diagram should show 3 windows: `(green), (yellow, blue, green), (orange)`.

If you have the courage, you can show the `cutBefore` variant which would emit an empty window first in the case of the source shown in the diagram: `(), (green, yellow, blue), (green, orange)`.

`windowWhile` is almost the same except it doesn't emit the green element: `(), (yellow, blue), (orange)`.

**Comment by schauder** [comment]
Fixed the diagram and made 3 out of them. I know the diagrams aren't perfect, but I kind of reached the limits of my non-existent-OmniGraffle skills.

**Comment by smaldini** [comment]
That's awesome @schauder !

**Comment by simonbasle** [comment]
I see the `.graffle` is part of the second commit, is that intentional?

**Comment by simonbasle** [comment]
is there really a modification of the `.graffle` file?

**Comment by simonbasle** [comment]
ok, @smaldini answered why: new diagrams were added to the `.graffle` container...
awesome work @schauder ! 🙇

**Pull request merged**
