### PR TITLE
fix #898 Add Context testing features

### LINKED ISSUE #898: Add `Context` testing features

### PR DESCRIPTION
**Pull request by simonbasle**
- set up an initial Context for a StepVerifier using options
 - set up expectations on the furthest reachable Context in the source
 chain

### CODE REVIEW

**Comment by simonbasle** [comment]
@rstoyanchev @sdeleuze what do you think of the API? (see the two sets of added tests)

**Comment by smaldini** [comment]
ping @rstoyanchev @sdeleuze should we move that to 3.1.2 to leave you time for further evaluation ? Also adding @poutsma -

**Comment by sdeleuze** [comment]
If you want a review from me yes, I am not familiar enough with `Context` support yet to give a relevant advice.

**Comment by simonbasle** [comment]
ping @rwinch: could you try that API out and see if from a `Context`-testing perspective it is missing something? I could produce a special "preview" snapshot of the branch if that helps.

**Pull request merged**
