### PR TITLE
fix #1745 Keep transform() and rename compose() to transformDeferred()

### LINKED ISSUE #1745: Deprecate Flux/Mono#compose
`transform` and `compose` difference is never obvious when looking at the names only.
`compose` can be achieved with `transform`+`defer`, so if we were to rationalize down to a single method, `transform` would be the 1s candidate.

### PR DESCRIPTION
**Pull request by simonbasle**
This commit mostly reverts d7b2271 and reworks the fix into keeping
the `transform()` method as it originally was, focusing on `compose()`.

The later is renamed to `transformDeferred`, conveying its relationship
to `defer()` in the sense that both apply per-subscriber. This allows
the two APIs to be easily discoverable in code completion while keeping
the most frequently version untouched.

In `ParallelFlux` we deprecate `composeGroup` and replace it with
`transformGroups`, furthering the same API alignment. The notion of
groups is already implying a per-subscriber nature, so the deferred
suffix is left out.

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @dfeist

**Comment by simonbasle** [comment]
@dfeist nothing to add? looking good to you?

**Comment by bsideup** [comment]
FTR here is a link that shows how it differs from 3.3.0.M2-ish state:
https://github.com/reactor/reactor-core/compare/40b06bd00147e92538bec376a185ab2fb2b7f3c3...1745-bis-composeRenaming

**Comment by dfeist** [comment]
> @dfeist nothing to add? looking good to you? (I see a thumbs up on the PR body, so I'll go ahead and merge 😉)

I didn't do a full compare but looks like revert + exactly what I suggested, so yes 👍  :-D

**Pull request merged**
