### PR TITLE
fix #730 Make GroupFlux#key non-nullable and update WindowPredicate

### LINKED ISSUE #730: Consider GroupedFlux#key non nullable
Will need to rework WindowPredicate grouped flux to sport a String key instead of T

### PR DESCRIPTION
**Pull request by rajinisivaram**

### CODE REVIEW

**Comment by smaldini** [comment]
I've been thinking about it a bit and I think we need to be more radical as toString is maybe too much an opinion. We might just not use GroupedFlux and instead plain flux. WDYT @simonbasle

**Comment by simonbasle** [comment]
I am indeed not sure that there is a lot of value in keeping the `key` for `WindowPredicate`... The previous version with `T` could unexpectedly retain object references, and the `toString` version will most likely produce some garbled strings (ie the predicate's string). @rajinisivaram let's keep this as-is except for the `FluxWindowPredicate` part which should now return a plain Flux. I can do a follow up PR on that if you prefer.

**Comment by rajinisivaram** [comment]
@simonbasle Are you working on a PR to convert `FluxWindowPredicate` from `GroupedFlux` to Flux? If not, I will do that today. Thanks.

**Comment by simonbasle** [comment]
@rajinisivaram nope I haven't started any work on that, so go ahead 😄 :+1:

**Comment by rajinisivaram** [comment]
@simonbasle Thanks, will open new PR.

**Pull request closed without merging**
