### PR TITLE
Fixes #86. Add mapOrFilter operator.

### LINKED ISSUE #86: Flux.map() and null-handling when wrapping existing blocking API's
The only way to do this currently is via the use of `flatMap` and `Mono.justOrEmpty()` which isn't as efficient and causes more allocations/stack.

One option is to introduce something in Flux e.g. `Flux.mapOrEmpty()` that behaves the same as `map` but drops message and does `request(1)` when null is returned, but I understand this clutters the primary API where nulls simply are not allowed.  So maybe an alternative is to implement something outside of Flux in something like `LegacyUtils` that can then somehow be pulled into and used in a Flux stream just in the cases where you need to deal with legacy API's that throw exceptions/return null.

This is somewhat related to: https://github.com/reactor/reactor-core/issues/80

### PR DESCRIPTION
**Pull request by dfeist**
@smaldini What do you think regarding this approach using boolean flag vs creating specific FluxSource implementations for mapOrFilter? Let me know and I can update/rework as required..

### CODE REVIEW

**Comment by smaldini** [comment]
Mhhh I'd go more for an individual operator.

**Comment by dfeist** [comment]
Ok,  i'll update.  That was first approach I took but wasn't sure it made
sense to duplicate all those classes..

**Comment by dfeist** [comment]
@smaldini Hang on,  I have seperate 'mapOrFilter operator already in PR. I was referring to if it made sense to duplicate FluxMap,  MonoMap etc.  Or if use of boolean is here is ok.  Take a look at PR and it'll be clear.  Please confirm.

**Comment by akarnokd** [comment]
I don't like this addition to `map` either. You should go with a separate operator. In addition, you neglected the fusion parts and didn't provide unit tests that verify the behavior.

**Comment by dfeist** [comment]
@akarnokd 👍 Will update.  Wanted to confirm approach before adding test..

**Pull request closed without merging**
