### PR TITLE
Use `contextWrite(f)` rather than subscriberContext(f) in docs

### PR DESCRIPTION
**Pull request by vovikdrg**
subscriberContext   is deprecated also in example contextWrite is used.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vovikdrg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2685)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2685) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vovikdrg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2685)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2685) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vovikdrg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2685)!

**Review by simonbasle — APPROVED** [review]
thanks for the fix to docs @vovikdrg 🙇

**Pull request merged**
