### PR TITLE
Fix Mono docstring return types

### PR DESCRIPTION
**Pull request by seants**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@seants Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2577)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2577) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by seants** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@seants This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Review by simonbasle — CHANGES_REQUESTED** [review]
thanks for the fix. I think it makes sense to improve the javadoc in the current maintenance branch, `3.3.x`, as well. Would you mind rebasing your PR branch on `3.3.x`? (the target branch can then be updated by editing the PR's title)

**Comment by seants** [comment]
Didn't quite get it but opened #2581 instead

**Pull request closed without merging**
