### PR TITLE
[Trivial]Simple documentation update

### PR DESCRIPTION
**Pull request by apuravchauhan**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@apuravchauhan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1821)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1821) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@apuravchauhan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1821)!

**Comment by simonbasle** [comment]
hey @apuravchauhan thanks for the simple fix :+1:
are you reading through the documentation? if so maybe it would make sense to wait a bit before merging so you get the opportunity of finding more such typos?
In any case I'll merge this by tomorrow, 6pm CEST.

**Comment by apuravchauhan** [comment]
@simonbasle Many thanks for the review and merge.

**Pull request merged**
