### PR TITLE
Fixes #283 Update .transform() in ParrellelFlux to support Function<P…

### LINKED ISSUE #283: Add .transformEach() in ParallelFlux to support Function<Publisher<U>, Publisher<V>>

### PR DESCRIPTION
**Pull request by dfeist**
…ublisher<U>, Publisher<V>>

### CODE REVIEW

**Comment by akarnokd** [comment]
This makes no sense. Returning a Publisher indicates you want to quit the parallel world but then you cast it back to ParallelFlux?

**Comment by dfeist** [comment]
@akarnokd Yes that make no sense, that's because i pushed the wrong thing, wasn't thinking. Look again..

**Comment by akarnokd** [comment]
The problem is that now you apply the default parallelization level to the Publisher source. There is `as` for general purpose conversion and `transform` for parallel-parallel conversion.

**Comment by dfeist** [comment]
@akarnokd I assumed from() had an instance of check, like Flux does. But even so, it would mean that whenever is Publisher from transform is returned parallel kicks in all over again when it shouldn't really.

I'll close out the issue and PR.

**Pull request closed without merging**
