### PR TITLE
fix #648 Make StepVerifier.withVirtualTime mutally exclusive

### LINKED ISSUE #648: Consider ways of improving StepVerifier/virtualtime parallel run experience
_From @simonbasle on March 10, 2017 10:16_

Streamline the `VirtualTimeScheduler` + `StepVerifier` experience so that it better works when running tests with a runner that has parallelism.

**Consider making VirtualTimeScheduler reference counted**
> *(old  idea)*
> ~~The idea could be to have a reference counter incremented on `VirtualTimeScheduler.getOrSet` calls that return an existing scheduler, then VTS's `dispose` method would do nothing but decrement the counter while it is still > 1.</i>~~

The reference count could be increased by `StepVerifier` before actual verification and decrease just after, right before the scheduler is `dispose()`.

**Caveat**
There is still a possibility that a race occurs where a VirtualTimeScheduler is shared by the two stepverifiers and disposed by the first while the second hasn't retained it yet.

In this light, it appears that the cons against running StepVerifier in parallel stack up:

1. sharing a VTS between several `StepVerifier`s is actually not that desirable since advancing time in 2 tests in parallel would have side effects on the others.
2. In the case where you *don't* want to share a VTS between tests, running tests in parallel can and will still result in side effects, as one VTS could be used through the factory by `Flux`/`Mono` instantiated in the other test. This is even less desirable since as soon as a Flux is created with the wrong VTS, it has the potential for infinite running the test (the StepVerifier would advance time in the wrong VTS).

Thus:

**Consider using synchronization** to ensure that no 2 `verify()` can run in parallel.

_Copied from original issue: reactor/reactor-addons#90_

### PR DESCRIPTION
**Pull request by simonbasle**
This commit adds a lock to the StepVerifier that is only used when
virtual time is activated, resulting in the VirtualTimeScheduler
activation, publisher verification and VTS reset to be mutually
exclusive with other StepVerifier.withVirtualTime verify() invocations.

This prevent different StepVerifier from side-effecting each other, as
the StepVerifier is installed using a global hook.

### CODE REVIEW

**Comment by simonbasle** [comment]
@jamalarm would you be able to locally build this branch and check if that solves your #1098 issue?

**Comment by Jamalarm** [comment]
Hi Simon,

Thanks for the potential fix! I can run this test for you. Probably not today but I will try and get it done by the end of the week.

**Comment by simonbasle** [comment]
@Jamalarm cool! it might get merged in the meantime so look out for this issue getting closed (that would make testing easier, as you could import `3.2.0.BUILD-SNAPSHOT` from `repo.spring.io/snapshots` instead of building locally).

**Comment by smaldini** [comment]
Any chance to consider a different approach such as ThreadLocal VTS ?

**Comment by simonbasle** [comment]
@smaldini no, it wouldn't help: the issue is that once you have parallel threads each enabling their own `VirtualTimeScheduler`, you have colliding `SchedulerFactories` and operator can and will see the wrong `VirtualTimeScheduler` as their default `Scheduler`, leading to hangs.

Here we force a sequential aspect to the "get vts, enable vts factory, reset factory and dispose vts" cycle inside `verify()` by using the lock.

**Comment by smaldini** [comment]
I think this seems good, maybe if possible try to compare the vts with the current global vts to limit it locking to global vts ?

**Comment by simonbasle** [comment]
@smaldini the step right after the locking is to set the `vts` as the global one. We really want to make the whole `verify()` mutually exclusive. The only scenario where this is not necessary is when virtual time isn't used.

**Comment by simonbasle** [comment]
@Jamalarm this is now merged and should land soon in a BUILD-SNAPSHOT near you, if you could try it and see if you can reproduce your issue 👍

**Comment by Jamalarm** [comment]
Hi Simon,

Thanks for fixing this so quickly, I will try and test it as soon as I can (things are somewhat mad over here at the moment so I don't have a huge amount of time 😞)

**Pull request merged**
