### PR TITLE
Minor fix on documentation on limitRate

### PR DESCRIPTION
**Pull request by chang-chao**

### CODE REVIEW

**Comment by simonbasle** [comment]
Hi @chang-chao, the current javadoc is actually correct but could be disambiguated a bit. It meant to say that seven consecutive `request` calls are made, each requesting the low tide which is `2` => 7 x `request(2)`. I'll fix the wording to make it clearer.

**Comment by chao-chang-paypay** [comment]
Hi @simonbasle , I'm still a little bit confused.
According to the [java doc](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#limitRate-int-int-
) of `Flux.public final Flux<T> limitRate(int highTide, int lowTide)`

>backpressure signals from downstream subscribers are split into batches capped at the provided highTide first, then replenishing at the provided lowTide

In example that  a downstream request of 14, with a highTide of 10 and a lowTide of 2 ,  I understand it that this operator will request(highTide:10) first, then request(lowTide:2) twice.  Is this understanding of mine correct?

**Comment by simonbasle** [comment]
@chang-chao you're right this is still confusing. The thing we should make clearer is that this operator isn't really looking at the downstream request, but rather assuming an unbounded request pattern. The intent of the operator is to "rebatch" a single large request into several smaller requests. It uses a "replenish" strategy: when it has seen x elements come through, it starts another batch. The `hightTide` vs `lowTide` distinction allows to chose a number for that x.

The smaller the `lowTide`, the more often it will replenish (potentially without a real need if downstream wasn't actually requesting a large amount).

The bigger the difference between `highTide` and `lowTide`, the bigger the potential overshoot for smaller downstream requests. Similarly, the smaller the downstream request(s), the larger the potential overshoot.

But all in all, this is intended to rebatch `request(Integer.MAX_VALUE)` into `request(highTide)`+`request(lowTide)`+...+`request(lowTide)`.

**Comment by chao-chang-paypay** [comment]
@simonbasle thanks for the explanation, finally got to understand it.
I draw it in the following table to illustrate the timings of 7 request(lowTide).

|             | 1 | 2          | 3 | 4          | 5 | 6          | 7 | 8          | 9 | 10         | 11 | 12         | 13 | 14         |
|-------------|---|------------|---|------------|---|------------|---|------------|---|------------|----|------------|----|------------|
| request(10) |   | request(2) |   | request(2) |   | request(2) |   | request(2) |   | request(2) |    | request(2) |    | request(2) |

**Pull request closed without merging**
