### PR TITLE
Fix the "Threading and Schedulers" sample code

### PR DESCRIPTION
**Pull request by pcdavid**
The code used to illustrate the section is incomplete: the thread it creates is never actually started, so the subscription never happens. Fix by explicitly starting it before join()-ing on it. Also add "throws InterruptedException" to make the code actually compile.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pcdavid Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1806)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1806) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pcdavid** [comment]
This looks like an "Obvious Fix", do I really need to sign the CLA as indicated by the bot?

**Comment by pivotal-issuemaster** [comment]
@pcdavid This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by simonbasle** [comment]
@pcdavid nope, changes to the documentation are not included in the obvious fix umbrella :(

**Pull request merged**
