### PR TITLE
Code optimize.

### PR DESCRIPTION
**Pull request by horizonzy**
Code optimize.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@horizonzy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2693)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2693) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@horizonzy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2693)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2693) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@horizonzy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2693)!

**Comment by simonbasle** [comment]
hey @horizonzy, thanks for the PR.

I did a little benchmarking of calling `toString` with the two approaches and if I'm interpreting gc profiler data correctly, the field approach doesn't really have a drawback in term of memory pressure (both normalized to 56 bytes per operation), but is slightly outperformed by the current approach in terms of ns/ops:

```
EnumToStringBenchmark.withStringField                                 avgt   10    41.844 ±   0.430   ns/op
EnumToStringBenchmark.withStringField:·gc.alloc.rate                  avgt   10  1020.093 ±   9.998  MB/sec
EnumToStringBenchmark.withStringField:·gc.alloc.rate.norm             avgt   10    56.000 ±   0.001    B/op
EnumToStringBenchmark.withStringField:·gc.churn.PS_Eden_Space         avgt   10  1019.240 ± 324.906  MB/sec
EnumToStringBenchmark.withStringField:·gc.churn.PS_Eden_Space.norm    avgt   10    55.920 ±  17.561    B/op

EnumToStringBenchmark.withStringField:·gc.count                       avgt   10    25.000            counts
EnumToStringBenchmark.withStringField:·gc.time                        avgt   10    10.000                ms
EnumToStringBenchmark.withoutStringField                              avgt   10    38.977 ±   0.402   ns/op
EnumToStringBenchmark.withoutStringField:·gc.alloc.rate               avgt   10  1094.813 ±  10.930  MB/sec 
EnumToStringBenchmark.withoutStringField:·gc.alloc.rate.norm          avgt   10    56.000 ±   0.001    B/op
EnumToStringBenchmark.withoutStringField:·gc.churn.PS_Eden_Space      avgt   10  1100.507 ± 297.096  MB/sec
EnumToStringBenchmark.withoutStringField:·gc.churn.PS_Eden_Space.norm avgt   10    56.315 ±  15.379    B/op
EnumToStringBenchmark.withoutStringField:·gc.count                    avgt   10    27.000            counts
EnumToStringBenchmark.withoutStringField:·gc.time                     avgt   10    12.000                ms
```

This was informative! 😄 
Since I don't really find a huge difference in readability between the two approaches, I'm going to avoid changing anything for the time being.
Thanks for the suggestion anyways 👍

**Pull request closed without merging**
