### PR TITLE
[wip] Make Context API non nullable

### PR DESCRIPTION
**Pull request by smaldini**
- add hasKey : boolean
- add getOrEmpty : Optional<T>

### CODE REVIEW

**Comment by smaldini** [comment]
It's wip but the point here is a get(...) that would return null would do so indefinitely. Context is immutable, a null key will never turn non null for a given ctx. User can still query presence of a key with hasKey or getOrEmpty (which superseed getOrDefault via Optionsl.orElse),

**Comment by simonbasle** [comment]
got it, wasn't sure what would be the most complicated to use between a nullable get or a throwing `get`... but in any case it should be marked as less than ideal, maybe even directly deprecated?

fair point on  `getOrEmpty().orElse()`, just thinking it just might be a bit more readable as a `getOrDefault()` alias / syntactic sugar?

**Comment by simonbasle** [comment]
@smaldini was thinking about:
 - [ ] adding `Context1`-`Context5` implementations (hidden, instead of the map one)
 - [ ] means of creating a `Context1` directly
 - [ ] maybe the same for sizes up to 5, but what of the key-value parameters (have a look at how java is planning on doing that for sequence literals?)

**Comment by simonbasle** [comment]
note on `putAll`: since this would return a `Context`, it clashes with `Map#putAll` in the `ContextN` implementation. I'm going with `putAllOf` but if you have a better suggestion @smaldini ...

**Comment by simonbasle** [comment]
@smaldini following @rwinch comment on `getOrDefault` I reinstated the nullabity of the default. Kept it as a separate commit for easy drop / revert, and rebased the rest, grouping your changes, my changes and an unrelated one (so this whole PR is ready for a `rebase-and-merge`).

**Pull request merged**
