### PR TITLE
[doc] Fix Mono#subscribeOn doc typo

### PR DESCRIPTION
**Pull request by seants**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@seants Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2286)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2286) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by seants** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@seants This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by simonbasle** [comment]
thanks @seants !

**Pull request merged**
