### PR TITLE
fix #1177 Operators to capture last visible Scheduler and go back to it

### LINKED ISSUE #1177: Access to the current scheduler
It is not possible to get a handle to the currently running scheduler. Though there are certain occasions where such a thing would be desired. Consider the following example:

```java
Flux.range(1, 2, 3)
	.flatMap(id -> {
		return Mono
			.fromCallable(() -> repository.findById(id))
			.subscribeOn(repositoryScheduler);
	})
	.map(record -> process(record))
	.subscribe(System.out::println);
```

Given, `repository.findById()` is blocking, it makes perfect sense to confine these calls to a dedicated thread pool, which is `repositoryScheduler` in this example. That being said, you would not want to occupy `repositoryScheduler` for consecutive `process(record)` calls. There you better switch to another threading context, preferably to the call initiating one. Though that turns out to be not possible:

```java
Flux.range(1, 2, 3)
	.flatMap(id -> {
		@Nullable Scheduler currentScheduler = /* What to type here? */;
                Scheduler effectiveScheduler = currentScheduler == null
                        ? /* some other scheduler */
                        : currentScheduler;
		return Mono
			.fromCallable(() -> repository.findById(id))
			.subscribeOn(repositoryScheduler)
			.publishOn(effectiveScheduler);
	})
	.map(record -> process(record))
	.subscribe(System.out::println);
```

Hence I ask for a simple aid like `Schedulers.current()` to use in cases similar to the above one. What if there are no schedulers involved? `Schedulers.current()` can just return `null`.

### PR DESCRIPTION
**Pull request by simonbasle**

### CODE REVIEW

**Comment by simonbasle** [comment]
cc @vy

**Comment by vy** [comment]
Great work @simonbasle! Thanks so much for taking time to work on the issue!

**Comment by smaldini** [comment]
I'm not too sure about the current form for this and we will surely evaluate it further in the current 3.3 cycle. Being explicit on the scheduler switch is also useful. Loom would provide us a better option obviously here but I'd love to see the current use case for this too now that can't be achieved with subscribeOn+publishOn.

**Comment by vy** [comment]
@smaldini, the usecase where `subscribeOn`+`publishOn` falls short of was detailed in #1177. In a nutshell, you `flatMap` to a library function which subscribes using its own scheduler but needs to publish it back to your scheduler so that you wouldn't be occupying its dedicated scheduler. The problem is 1) as a caller, you don't know that the library us switching schedulers, and 2) as a callee, library doesn't know how to release its thread and let the execution continue in the caller scheduler. Does this help?

**Comment by bsideup** [comment]
@vy 
> needs to publish back to your scheduler so that you wouldn't be occupying its dedicated scheduler

There are two scenarios:
1. you need to do some blocking/CPU-heavy call after it. In this case, you would use `publishOn` and friends anyways
2. you need to perform some non-blocking, non-CPU-heavy call. In this case, IMO it does not make any sense to move it to a separate scheduler.

Keep in mind that `publishOn` is an expensive operation

> 1) as a caller, you don't know that the library us switching schedulers

You don't need to, really. 

>  2) as a callee, library doesn't know how to release its thread and let the execution continue in the caller scheduler. 

You shouldn't care. The only thing you care is the thread starvation (caused by either IO or CPU-heavy tasks), but there is a common consumer's rule - if you need to perform some heavy operation, explicitly move it to a dedicated scheduler.

**Comment by vy** [comment]
@bsideup Thanks for taking time to check the issue.

> you need to do some blocking/CPU-heavy call after it.
> In this case, you would use publishOn and friends anyways

How would you use *`publishOn` and friends* given you don't know the scheduler of the caller or the callee?

Let me explain the situation using a concrete example:

1. The service receives HTTP requests, in particular of type *assortment*. HTTP requests are handled by Netty I/O loop. In order to not block that, you pass the received HTTP request to `assortment-scheduler`. (*Assortment* is not the only handler in that I/O loop, hence the dedicated scheduler.)
2. Later on you need to fetch a row from the database. You call `db.find(assortment)`. Since there are many other components of the application reaching out for `db`, it strives to do the following:
    1. Execute the operation in its own dedicated `jdbc-scheduler` to not block the caller scheduler.
    2. Once the result is ready, pass the execution back to the caller scheduler to not occupy itself for other requests coming from other components of the application.

Here the last step is not possible since `db` doesn't have an access to the caller scheduler.

Does this make more sense? Is my reasoning incorrect?

**Comment by bsideup** [comment]
> Once the result is ready, pass the execution back to the caller scheduler to not occupy itself for other requests coming from other components of the application.
>> to not occupy

Why would you "occupy" the thread if the only next thing you will do is a non-blocking, lightweight operation?

Reactive programming abstracts the threading, and almost the only reason you need to care about the thread is because of the blocking I/O and heavy computations.

Consider the following example:
```java
doSomethingInDB().flatMap(user -> fetchFriends(user))
```

`user` will be emitted on DB's thread, the `flatMap'` mapper will be executed in that thread, but, since it will only push to the queue and *maybe* trigger the queue draining, there is no good reason to switch the threads back to Netty's scheduler. In fact, it will only increase the amount of work to do, and the amount of consumed CPU.

Another example:
```java
doSomethingInDB().publishOn(blockingFriendlyScheduler).map(user -> fetchFriendsSync(user))
```

Here we know that `fetchFriendsSync` is a blocking operation, and make sure that the processing will be done on a special thread pool for the blocking operations. We only care about the rule "do not run blocking/heavyweight operations on non-blocking threads"

**Comment by vy** [comment]
Consider the following: `.flatMap(db::fetchUsingDedicatedSched).map(bar::blockingCall)`. Wouldn't `bar::blockingCall` will be occupying the dedicated db sched? That is, its resources will be used by a `blockingCall` which has nothing to do with `db`. How can `db` opt out from this?

**Comment by bsideup** [comment]
> Consider the following: .flatMap(db::fetchUsingDedicatedSched).map(bar::blockingCall)

I would say this code smells. The blocking calls should not be made without a strict control of the schedulers, and here you implicitly inherit the dedicated scheduler.

**Comment by vy** [comment]
I think this is a pretty reasonable case, even though it conflicts with your sense of good smell. Now replace `db::fetchUsingDedicatedSched` with `library::doSth` and there goes your perfectly valid case for needing to return back to the caller scheduler. The problem is `library` does not know the context it has been called from and does not want to spend its scheduler time on irrelevant tasks.

**Comment by bsideup** [comment]
> I think this is a pretty reasonable case, even though it conflicts with your sense of good smell.

Well, this is not my personal opinion. Running blocking operations on non-blocking threads is a dangerous, performance critical mistake. This is why we created [BlockHound](https://github.com/reactor/BlockHound) which helps detecting such calls. Every blocking call should be explicitly redirected to a dedicated scheduler.

> Now replace `db::fetchUsingDedicatedSched` with `library::doSth` and there goes your perfectly valid case for needing to return back to the caller scheduler

Sorry, I still don't see why we need to return to the caller scheduler here.

> The problem is library does not know the context it has been called from and does not want to spend its scheduler time on irrelevant tasks.

This is not library's concern, really. As long as library's threads are not blocked, we're good. You can have tens of schedulers but the CPUs count will remain static, and it makes little to no sense to move the non-blocking lightweight operation to another pool which will run on the same CPU

**Comment by ttddyy** [comment]
Hi, I just stumbled upon this usecase and thought about this ticket.

I am writing a library which we intend to use in both spring-mvc and spring-webflux environment.
We have a spring-security `AuthenticationManager` bean. To allow reusing this bean in reactive env, spring-security provides [`ReactiveAuthenticationManagerAdapter`](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/authentication/ReactiveAuthenticationManagerAdapter.java#L32).
The problem(?) is that this auth-manager-adapter performs authentication logic in separate schedular(elastic, line-43).
This means: every web request coming to the server initially handled by `reactor-http-nio-*` threads.
However, most of the request go through auth flow, and eventually they will switch to elastic scheduler, and then rest of the controller/service logic will be performed on elastic scheduler.

I'm not sure after auth logic, whether the control should go back to `reactor-http-nio-*` threads to process the rest of controller/service logic or not.
But, if we have a notion of the original scheduler and a way to go back, then, controller/service logic can be processed on original scheduler.

**Comment by bsideup** [comment]
@ttddyy 

> I'm not sure after auth logic, whether the control should go back to reactor-http-nio-* threads to process the rest of controller/service logic or not.

It shouldn't. Spring Security stores the auth info in the context, not thread.
For the other things, see my previous comments in this issue :)

**Pull request closed without merging**
