### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by chemicL**
- bytebuddy 1.12.18 -> 1.12.20
- junit 5.9.1 -> 5.9.2
- blockhound 1.0.6.RELEASE -> 1.0.7-RELEASE
- mockito 4.8.1 -> 4.11.0

### CODE REVIEW

**Comment by chemicL** [comment]
Looks like the build gets broken by ByteBuddy 1.12.21 (https://github.com/raphw/byte-buddy/compare/byte-buddy-1.12.20...byte-buddy-1.12.21) - investigating.

**Comment by chemicL** [comment]
I'm trying to clarify whether this is a regression or we were using it based on some assumptions that do not have to hold. https://github.com/raphw/byte-buddy/issues/1400

**Comment by chemicL** [comment]
For the time being, only bumping to 1.12.20 of ByteBuddy.

**Comment by chemicL** [comment]
https://github.com/raphw/byte-buddy/issues/1400 is resolved in 1.12.23 of ByteBuddy so that version is now used.

**Review by OlegDokuka — APPROVED** [review]

**Comment by chemicL** [comment]
Merged to main in e1319e7081ce38021541be574c5b6f4fd1a8771f

**Pull request merged**
