### PR TITLE
Make use of CompletionStage#handle instead of `whenComplete`

### PR DESCRIPTION
**Pull request by He-Pin**
Which has better performance.
https://github.com/line/armeria/pull/1596

### CODE REVIEW

**Review by OlegDokuka — APPROVED** [review]

**Comment by OlegDokuka** [comment]
@chemicL this should be forwardmerged. Lazy one uses same method as well

**Comment by chemicL** [comment]
I just noticed #3222 which addresses the issue on `main`. I suppose we'll need to forward-merge but discard the change and take the one from the other PR instead.

**Comment by He-Pin** [comment]
@chemicL Yes ,I created two PR, one for 3.4.x and one for main, I saw @OlegDokuka did more optimizations of memory usage on the current main branch:)
This is my first time contribution

**Comment by OlegDokuka** [comment]
@He-Pin second is going to be closed since we use forward merge to keep both branches connected

**Comment by He-Pin** [comment]
But in the second one, you fold the `BiConsumer` to `MonoCompletionStageSubscription`. so I do it in a separated PR. or will you backport that memory optimization to 3.4.x?

**Comment by He-Pin** [comment]
image

jmh:run -i 5 -wi 5 -f1 -t1 .CompletionStageBenchmark.

```scala
package bench

import org.openjdk.jmh.annotations._

import java.util.concurrent.CompletableFuture
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit

@State(Scope.Benchmark)
@OutputTimeUnit(TimeUnit.SECONDS)
@BenchmarkMode(Array(Mode.Throughput))
class CompletionStageBenchmark {
  val ex = new RuntimeException("ex")

  @Benchmark
  def benchWhenCompleteFailedSync(): Unit = {
    val future = new CompletableFuture[Int]()
    future.completeExceptionally(ex)
    val latch = new CountDownLatch(1)
    future.whenComplete((_, _) => latch.countDown())
    latch.await()
  }

  @Benchmark
  def benchWhenCompleteSuccessSync(): Unit = {
    val future = new CompletableFuture[Int]()
    future.complete(1)
    val latch = new CountDownLatch(1)
    future.whenComplete((_, _) => latch.countDown())
    latch.await()
  }

  @Benchmark
  def benchHandleFailedSync(): Unit = {
    val future = new CompletableFuture[Int]()
    future.completeExceptionally(ex)
    val latch = new CountDownLatch(1)
    future.handle((_, _) => latch.countDown())
    latch.await()
  }

  @Benchmark
  def benchHandleSuccessSync(): Unit = {
    val future = new CompletableFuture[Int]()
    future.complete(1)
    val latch = new CountDownLatch(1)
    future.handle((_, _) => latch.countDown())
    latch.await()
  }

}

```

**Pull request merged**
