### PR TITLE
#943 fixed issue with scheduling of a request to upstream

### PR DESCRIPTION
**Pull request by OlegDokuka**
see #943

### CODE REVIEW

**Comment by smaldini** [comment]
We don't need the requestOnSeparateThread option yet, especially for Mono

**Comment by OlegDokuka** [comment]
@smaldini, do not know what your shortness means but I will remove that option. But it is strange, because Reactive 4JavaFlow does have this option

**Comment by OlegDokuka** [comment]
I have no idea why this test got failed, actually even not related tests got failed (https://travis-ci.org/reactor/reactor-core/jobs/302970023#L7913)

**Comment by simonbasle** [comment]
All three tests relate to subscribeOn though, right? Looks like it sends tests into a livelock and tests hang for 10 minutes :(

**Comment by OlegDokuka** [comment]
@simonbasle Actually, I have not touch FluxSubscribeOn at all, thus I'm saying that it is strange 😢

**Comment by OlegDokuka** [comment]
Whoohoo, my first contribution 🎆

**Pull request merged**
