### PR TITLE
style(core): style refactored for MpscLinkedQueue, Queues;

### PR DESCRIPTION
**Pull request by h1alexbel**

### CODE REVIEW

**Comment by OlegDokuka** [comment]
@h1alexbel can you make sure everything is aligned with the original JCTools `MpscLinkedQueue`? I prefer to keep the code aligned rather than styled properly. Thx

**Comment by h1alexbel** [comment]
> @h1alexbel can you make sure everything is aligned with the original JCTools `MpscLinkedQueue`? I prefer to keep the code aligned rather than styled properly. Thx

@OlegDokuka made it aligned. Please, check.

**Comment by chemicL** [comment]
I'm uncertain what's happening in this PR, as the formatting changes make it impossible to understand what substance is being touched. According to the contributing guidelines, this PR violates the [Code style](https://github.com/reactor/.github/blob/main/CONTRIBUTING.md#art-code-style) section. I'd be in favour of closing this PR unless this change is outside of the formatting area.

**Comment by chemicL** [comment]
Closing as discussed with @OlegDokuka

**Pull request closed without merging**
