### PR TITLE
fix #1981 Fix marble diagram of withLatestFrom

### LINKED ISSUE #1981: Incorrect marble diagram for withLatestFrom
I believe the "marble" diagram in the documentation of the `withLatestFrom` [here](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#withLatestFrom-org.reactivestreams.Publisher-java.util.function.BiFunction-) is not correct (`C2` and `D3` should not have been emitted). In fact, it does not agree with the one found in [rxmarbles](https://rxmarbles.com/#withLatestFrom), [rxjs](https://rxjs.dev/api/operators/withLatestFrom), or [rxjava](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#withLatestFrom-java.lang.Iterable-io.reactivex.functions.Function-)

## Motivation

Based on the documentation of other reactive libraries `withLatestFrom` is similar to `combineLatest` but it only emits items when the single source Flux emits an item (not when any of the Fluxes that are passed to the operator do, as `combineLatest` does).

## Desired solution

Change the documentation and the diagram according to the offered functionality.

### PR DESCRIPTION
**Pull request by sgsfak**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sgsfak Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1984)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1984) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sgsfak Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1984)!

**Comment by simonbasle** [comment]
thanks for submitting this @sgsfak. Note I have rebased your branch on `3.2.x` in order to merge this in the correct branch. I have pushed this on your fork `master`.

**Comment by sgsfak** [comment]
> thanks for submitting this @sgsfak. Note I have rebased your branch on `3.2.x` in order to merge this in the correct branch. I have pushed this on your fork `master`.

Thank you, and sorry for messing up with branches :-)

**Comment by simonbasle** [comment]
not a problem, I should have made it clear when suggesting you do a PR ;)

**Pull request merged**
