### PR TITLE
Reference Guide: PublisherProbe + Processors writeup + Context + minor fixes

### PR DESCRIPTION
**Pull request by simonbasle**
This pull request fleshes out missing sections of the reference guide:
 -  add the topic of `PublisherProbe` in the *testing* section
 -  describe each `Processor` in the *core features* section (actually isolating the content for processors in a dedicated source file).
 - add a short mention of `FluxRefCountGrace` in the `ConnectableFlux` section.

cc @Buzzardo 

Part of #404 
Also partly covers #838 (`Context`)

### CODE REVIEW

**Comment by simonbasle** [comment]
@smaldini to review the processor writeup, you can use this [rich diff](https://github.com/reactor/reactor-core/pull/853/files?short_path=ba46199#diff-ba46199694c92b43e7cd3d3f41fc6843)

@rwinch I added a section about `PublisherProbe` in the reference guide (see [this rich diff](https://github.com/reactor/reactor-core/pull/853/files?short_path=e31be46#diff-e31be4639c45f923ba3d6c2f815d4857)). Does that sound like it demonstrates your initial issue and how to overcome it with the probe class?

**Comment by rwinch** [comment]
@simonbasle Thanks for reaching out. It does demonstrate the issue that I was encountering. I might question if we need to discuss the `AtomicBoolean` route as that appears to be more information that the user needs since it isn't optimal. Perhaps removing that piece?

**Comment by simonbasle** [comment]
(rebased on master + grouped into rebase-mergeable commits)

**Comment by simonbasle** [comment]
`pr-fast-track`, will need full technical review by @smaldini later ;)

**Pull request merged**
