### PR TITLE
disposed worker should reject scheduling a task with zero period

### PR DESCRIPTION
**Pull request by lerencao**
See #1411 for details.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lerencao Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1412)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1412) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by simonbasle** [comment]
@lerencao thanks for the PR. This brings another question: we need to double check if `tasks.add(task)` should be used for a delay of 0. This is done in `workerSchedule`, but as you found out not in `workerSchedulePeriodically`... If it turns out to be a bad idea, the `add` attempt can be replaced by a `if (tasks.isDisposed())` check.

**Comment by lerencao** [comment]
I think it should be. 
If `tasks.add(task)` is not used, the periodic task cannot be cancelled after parent tasks is disposed.

**Comment by simonbasle** [comment]
you're right. there are two cases here:
 - zero `period` but *positive* `initialDelay`: the `initialDelay` will prevent burst of rescheduling (due to the zero period), so it totally makes sense to have this one cancellable
 - zero `period` and zero `initialDelay`: this results in a lot of immediate tasks being repetitively scheduled, unless each task takes some time to complete. less sense in being cancellable but doesn't hurt to track these I think.

I'd like to improve the tests on top of that PR though.

**Comment by simonbasle** [comment]
I'll edit your test case to complete the cancellation and (new) rejected tests to cover all 4 cases (0 period with and without delay, periodic with and without delay) and this will be good to merge.

**Pull request merged**
