### PR TITLE
OSGi bundle: don't import com.google twice

### PR DESCRIPTION
**Pull request by magnet**
Fix for #386

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@magnet Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=387)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=387) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@magnet Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=387)!

**Comment by magnet** [comment]
It's an obvious fix but I've signed the CLA in case I provide further pull requests later.

**Comment by simonbasle** [comment]
great, thanks! I'll change the commit message to follow the style we usually use and merge it right away ;)

**Pull request merged**
