### PR TITLE
Correct typo in metrics.adoc

### PR DESCRIPTION
**Pull request by jarredhiggs**
Corrected typo

### CODE REVIEW

**Review by simonbasle — COMMENTED** [review]
the linked page doesn't even list that metric anymore. I wonder if listing metric names makes sense at all here 🤔 wdyt @jarredhiggs?

**Comment by jarredhiggs** [comment]
Linking to Micrometer's documentation should be enough IMO.

If we'd rather keep some of the metrics listed here, we should probably update them to use the same naming convention as the rest of the article, though.

**Comment by simonbasle** [comment]
@jarredhiggs what do you mean by naming conventions in the article? the names of these metrics are defined by Micrometer's own instrumentation of JVM classes.

**Comment by jarredhiggs** [comment]
@simonbasle I'm referring to MicroMeter's [NamingConvention](https://www.javadoc.io/doc/io.micrometer/micrometer-core/1.0.6/io/micrometer/core/instrument/config/NamingConvention.html).  In `metrics.adoc`, an underscore-separator naming convention is used for the metric names listed in lines 32-36, whereas the rest of the page uses the dot-separator naming convention. MicroMeter will automatically convert its output to whatever naming convention is expected by all the major monitoring platforms, so we could use whichever convention we want in the documentation, but it should be consistent.

Unless, of course, I'm misunderstanding something. 🤔

**Comment by simonbasle** [comment]
ah, got it thanks for the explanation. Let's simply remove these lines 32-36 with the underscores and simply link to Micrometer's documentation.

**Review by simonbasle — APPROVED** [review]

**Pull request merged**
