### PR TITLE
implements new version of WindowTimeout

### LINKED ISSUE #1099: WindowTimeout backpressure
### Expected behavior
`windowTimeout` respects the backpressure

### Actual behavior
**Not verified if expected or not:**
` The receiver is overrun by more signals than expected (bounded queue...)`

### Steps to reproduce
```java
Flux
        .generate(sink -> {
            System.out.println("generate");
            sink.next(UUID.randomUUID().toString());
        })
        .log("source", Level.INFO, SignalType.REQUEST)
        .limitRate(5)
        .windowTimeout(10, Duration.ofSeconds(2))
        .concatMap(batch -> batch.delayElements(Duration.ofMillis(200)))
        .blockLast()
```

### Reactor Core version
3.1.4.RELEASE

### JVM version (e.g. `java -version`)
Any

### PR DESCRIPTION
**Pull request by OlegDokuka**
closes #1099 

Signed-off-by: Oleh Dokuka <odokuka@vmware.com>

### CODE REVIEW

**Comment by joshfree** [comment]
Tagging @jonathangiles @anuchandy

**Comment by OlegDokuka** [comment]
@anuchandy updated implementation a bit. Also, added your tests which demonstrate that the new impl is working as expected (probably).

Also, just FYI - operators like publishOn have a `prefetch` buffer which may store some amount of collected elements. Also, I added subscribeOn to decouple the requester thread from the producer thread

**Comment by JonathanGiles** [comment]
Thank you @OlegDokuka - we will get to testing this straight away.

**Comment by anuchandy** [comment]
Hi @OlegDokuka, thanks of the updated impl and cleaning up the test. I’ll continue testing the impl. 

Just curious, the stress test you mentioned - is it a part of reactor-core public repo or is it kind of validations done internally?

**Comment by OlegDokuka** [comment]
@anuchandy all existing stress tests could be found there -> https://github.com/reactor/reactor-core/tree/main/reactor-core/src/jcstress/java/reactor/core/publisher

**Comment by anuchandy** [comment]
Thanks, @OlegDokuka. As part of validations, I'm trying to understand the various backpressure involved, IIUC, considering the following code, there are two categories of backpressure - 

```java
Flux<Event> source = ..
Flux<Flux<Event>> sourceWindowed = source.windowTimeout(500, Duration.ofSeconds(3), ..);
```

1. Backpressure to `source` for events.
2. Backpressure to `sourceWindowed` for windows.

If we chain an operator with `prefetch` buffer (e.g., size 50) to `sourceWindowed` - does that mean 

1. It results in requesting 50 "windows" to `sourceWindowed` 
2. which internally requests 50 * 500 "events" to the `source` 
3. with the timeout constrain of 3 sec applied to each of the 50 windows

Is this understanding correct?

4. Is there a setting that caps the number of concurrent "windows" in the above case? (e.g., capped by the threads in the scheduler)

**Comment by OlegDokuka** [comment]
> Backpressure to source for events.

there is a backpressure equal to the max elements in the window. So

> Backpressure to sourceWindowed for windows.

it depends on the downstream. For example using `concatMap(fn, 0)` with zero prefetch setup, the demand going to be equal to 1. Once downstream prefetched a value from sourceWindowed the upstream going to receive up to `maxWindowSize` (which is in example 500. you may wonder why up to 500 - because if the previous window did not fulfill completely, then the next window will not request 500 again, but rather the diff between what received and what is remaining to be sent from the `source`).

> It results in requesting 50 "windows" to sourceWindowed

yes, if downstream prefetches 50, then it will be stored in the `requested` value.

> which internally requests 50 * 500 "events" to the source

nope, only 500 can be requested at a time.

> with the timeout constrain of 3 sec applied to each of the 50 windows

since only a single window can be opened at a time. There is not possible intersections between windows in that operator



Hope, that explains everything,
Oleh

**Comment by anuchandy** [comment]
Thank you, @OlegDokuka, for the answers. Using the diff for the demand makes sense; we don't want to overread from the main source; combining that with the prolonged window (if no demand for new window) collecting any events after the timeout seems to ensure no event loss.

I am continuing the test/profiling. Please tag me if you amend new commit(s), that are ready for validation.

**Comment by OlegDokuka** [comment]
@anuchandy working on more fixes... will ping you

**Comment by JonathanGiles** [comment]
Any status update here @simonbasle and @OlegDokuka ? Thanks!!

**Comment by OlegDokuka** [comment]
@JonathanGiles it is coming. Stay tuned.

**Comment by JonathanGiles** [comment]
Thanks for the update, much appreciated. We are very eager to see this improvement!

**Comment by anuchandy** [comment]
thanks @OlegDokuka, just tag me when the next draft is ready, so that I can pull it to test via our use cases

**Comment by anuchandy** [comment]
Hi @OlegDokuka, I hope you're doing good. Just checking, how is the work progressing? P lease let me know once you have the next draft to test.

**Comment by OlegDokuka** [comment]
@anuchandy this PR is superseded by #3054 the which is about the o be merged and going to be released next Tuesday. Stay tuned

**Comment by OlegDokuka** [comment]
close since is superseded by #3054

**Pull request closed without merging**
