### PR TITLE
see #903 Improve OSGI Import-Package

### PR DESCRIPTION
**Pull request by simonbasle**
- kotlin packages are optional
 - com.google and javax.annotation (JSR 305) are excluded

### CODE REVIEW

**Comment by simonbasle** [comment]
@magnet how does that look?

this gives the following Import-Package and Export-Package:

```
Import-Package: org.slf4j;resolution:=optional;version="[1.5.4,2)",kot
 lin;resolution:=optional,kotlin.collections;resolution:=optional,kotl
 in.jvm;resolution:=optional,kotlin.jvm.functions;resolution:=optional
 ,kotlin.jvm.internal;resolution:=optional,kotlin.jvm.internal.markers
 ;resolution:=optional,kotlin.reflect;resolution:=optional,kotlin.sequ
 ences;resolution:=optional,org.reactivestreams;version="[1.0,2)",reac
 tor.core;version="[3.1,4)",reactor.core.publisher;version="[3.1,4)",r
 eactor.core.scheduler;version="[3.1,4)",reactor.util;version="[3.1,4)
 ",reactor.util.annotation;version="[3.1,4)",reactor.util.concurrent;v
 ersion="[3.1,4)",reactor.util.context;version="[3.1,4)",reactor.util.
 function;version="[3.1,4)",sun.misc
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Tool: Bnd-3.4.0.201707252008
Export-Package: reactor.adapter;version="3.1.1.BUILD-SNAPSHOT";uses:="
 org.reactivestreams,reactor.core.publisher",reactor.core;version="3.1
 .1.BUILD-SNAPSHOT";uses:="org.reactivestreams,reactor.util.annotation
 ,reactor.util.context,reactor.util.function",reactor.core.publisher;v
 ersion="3.1.1.BUILD-SNAPSHOT";uses:="kotlin,kotlin.jvm.functions,kotl
 in.jvm.internal.markers,kotlin.reflect,kotlin.sequences,org.reactives
 treams,reactor.core,reactor.core.scheduler,reactor.util.annotation,re
 actor.util.concurrent,reactor.util.context,reactor.util.function",rea
 ctor.core.scheduler;version="3.1.1.BUILD-SNAPSHOT";uses:="reactor.cor
 e",reactor.util;version="3.1.1.BUILD-SNAPSHOT",reactor.util.annotatio
 n;version="3.1.1.BUILD-SNAPSHOT",reactor.util.concurrent;version="3.1
 .1.BUILD-SNAPSHOT",reactor.util.context;version="3.1.1.BUILD-SNAPSHOT
 ";uses:="reactor.util.annotation",reactor.util.function;version="3.1.
 1.BUILD-SNAPSHOT";uses:="kotlin,reactor.util.annotation"
```

**Comment by magnet** [comment]
@simonbasle The manifest looks OK but what about the directive to forcefully remove `com.google`? If there is no dependency on that package in the bytecode, there should be no need to have that. If there is indeed a dependency and the import is not present, that could lead to issues at runtime.

Do you know if there's anything actually used in package `com.google`?

**Comment by simonbasle** [comment]
ah good point, that had probably just been added there because of the com.google.findbug dependency, but this is the javax.annotation packages...

**Comment by magnet** [comment]
BTW I don't know how it fits the Kotlin story, but having the extensions in a separate package might be a good idea to avoid packages dragging optional dependencies... :-)

**Comment by simonbasle** [comment]
@magnet we aligned our Kotlin story with that of Spring Framework: first-class support with no separate artifacts, Kotlin support for each reactor artifact is bundled in the same jar (for now core, soon addons as well).

**Comment by magnet** [comment]
@simonbasle I was talking about different Java packages, not different artifacts/JARs. WDYT?

**Comment by simonbasle** [comment]
Ah my bad! by convention most of the time Kotlin extensions are in the same package as the Java classes they extend, so that's the approach we took too...

At this point, changing the package would be breaking the APIs anyway so unfortunately that ship has sailed 😞 🚢

**Comment by magnet** [comment]
OK! I was under the impression that Kotlin support was experimental and may break until the dust settles. 
I believe it would make maintenance easier if it was in another package, both for OSGi and what I know of JPMS. 
Other than that :+1: for the pull request, but I haven't had time to test it in a running container. I am on the run now so either I find 10 minutes in later today or I won't be able to test it for the week to come.

**Comment by simonbasle** [comment]
I'll defer until tomorrow to merge then, just in case you find some time for testing 🙇

**Pull request merged**
