### PR TITLE
FIFO execution for executor service scheduler

### LINKED ISSUE #2715: switchOnFirst multithread issue?
We have upgraded Spring Boot to 2.4.6 (form 2.3.x). It is including reactor 3.4.6. From that point we see time to time some strange NPE that I do not see how it can happen. I see that there was a recent change in switchOnFirst related to threading: #2671 #1496 We also use it with rsocket.

## Expected Behavior
switchOnFirst should not pass null to downstream and handle the switch properly with multiple threads (publishOn, subscribeOn).

## Actual Behavior
```java
    public <R, M> Flux<R> buildRequestChannel(Publisher<? extends M> request, 
        Function<M, ByteBuffer> encoder, Function<Payload, R> decoder) {
        return 
            rSocket.flatMapMany(socket -> socket.requestChannel(
                Flux.from(request)
                .publishOn(scheduler)
                .map(encoder) <- Creates ByteBuffer (impossible to be null as it is ByteBuffer.wrap())
                .switchOnFirst((signal, inner) -> {
                    if (signal.hasValue()) {
                        Payload firstPayload = DefaultPayload.create(signal.get(), encodeMetadata());
                        return Mono.just(firstPayload)
                            .concatWith(inner.skip(1).map(DefaultPayload::create));
                    }
                    return inner.map(DefaultPayload::create);
                })
                .transform(f -> transformSend.apply(f))) <-- HERE
            .publishOn(scheduler)
            .transform(f -> transformReceive.apply(f))
            .map(decoder))
            .onErrorMap(applicationExceptionMapper())
            .contextWrite(ctx -> ctx.put(ORIG_URL, target));
    }
```

HERE line is our monitoring transformer where e simply count bytes of DefaultPayload, but data is null. We call there that getData(). The only possibility is to get null to DefaultPayload.create in the code you see (upstream cannot generate null.) 

FluxSwitchOnFirst is playing a lot with variables around "firstValue" which are not volatile so maybe it 

```
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.duplicate()" because "this.data" is null
    at io.rsocket.util.DefaultPayload.getData(DefaultPayload.java:138)
    at com.ca.apm.common.rpc.RSocketServices.lambda$19(RSocketServices.java:516)
    at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:184)
    at reactor.core.publisher.FluxSwitchOnFirst$SwitchOnFirstControlSubscriber.onNext(FluxSwitchOnFirst.java:853)
    at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onNext(FluxConcatArray.java:177)
    at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
    at reactor.core.publisher.FluxSkip$SkipSubscriber.onNext(FluxSkip.java:86)
    at reactor.core.publisher.FluxSwitchOnFirst$SwitchOnFirstMain.tryDirectSend(FluxSwitchOnFirst.java:728)
<-- HERE firstValue was resolved to null ???
    at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.sendFirst(FluxSwitchOnFirst.java:686)
    at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.request(FluxSwitchOnFirst.java:630)
    at reactor.core.publisher.FluxSkip$SkipSubscriber.onSubscribe(FluxSkip.java:78)
    at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.subscribe(FluxSwitchOnFirst.java:672)
    at reactor.core.publisher.Flux.subscribe(Flux.java:8235)
    at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:208)
    at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:80)
    at reactor.core.publisher.Flux.subscribe(Flux.java:8235)
<-- HERE firstValue cannot be null
    at reactor.core.publisher.FluxSwitchOnFirst$AbstractSwitchOnFirstMain.onNext(FluxSwitchOnFirst.java:483)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
    at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:83)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)
    at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:237)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
    at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drainRegular(FluxGroupBy.java:567)
    at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.drain(FluxGroupBy.java:652)
    at reactor.core.publisher.FluxGroupBy$UnicastGroupedFlux.subscribe(FluxGroupBy.java:718)
    at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
    at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:57)
    at reactor.core.publisher.Flux.subscribe(Flux.java:8235)
    at io.rsocket.core.RequestChannelRequesterFlux.subscribe(RequestChannelRequesterFlux.java:115)
```

## Steps to Reproduce
I am not able to reproduce it in a test. Only our application code.

## Possible Solution
No idea yet. Maybe volatile variables for: isInboundRequestedOnce, isFirstOnNextReceivedOnce, firstValue.

## Your Environment
Spring Boot to 2.4.6 (form 2.3.x)
Reactor Core 3.4.6
RSocket 1.1.0

### PR DESCRIPTION
**Pull request by koldat**
It tries to fix #2715 and #2165.

### CODE REVIEW

**Comment by OlegDokuka** [comment]
@koldat thank you for creating this PR.

Can you please look at this impl -> https://github.com/ReactiveX/RxJava/blob/17366435ba5df7f37b97ad50e38748bf3917ff9b/src/main/java/io/reactivex/rxjava3/internal/schedulers/TrampolineScheduler.java#L65 and port it since that is something we were talking with @simonbasle initially

**Comment by koldat** [comment]
@OlegDokuka I am aware of trampoline, but this implementation is much cleaner I think.

1. It follows FIFO by definition (completable futures cannot change order). This chain of futures is connected to worker instances.
2. Performance is actually same (or little better):
```java
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();
            Flux<Integer> [] inputs = new Flux[8];
            for (int p = 0; p < 8; p++) {
                inputs[p] = Flux.range(0, 100000)
                    .publishOn(s, 1)
                    .subscribeOn(s)
                    //.log()
                    .limitRate(1);
            }
            Flux.merge(inputs)
                .limitRate(1)
                .subscribeOn(s)
                .blockLast();
            
            log.info("Took: {}", (System.currentTimeMillis() - start));
        }
```
After 10 rounds:
CompletableFutures: 18:43:23.018 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 1075
BoundedElastic: 18:42:26.066 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 3371
Trampoline: 18:45:27.929 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 1143

When test is not that crazy:
```java
        for (int i = 0; i < 10; i++) {
            long start = System.currentTimeMillis();
            Flux.range(0, 10000000)
                .publishOn(s, 1)
                .limitRate(1)
                .subscribeOn(s)
                .blockLast();
            
            log.info("Took: {}", (System.currentTimeMillis() - start));
        }
```

After 10 rounds:
CompletableFutures: 18:47:24.445 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 169
BoundedElastic: 18:48:10.379 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 155
Trampoline: 18:48:34.005 [main] INFO com.ca.apm.common.SwitchOnFirstTest - Took: 211

Or suggest other test.

**Comment by koldat** [comment]
BTW compared to boundedElastic it has one great feature. It shared the whole pool so in case something is stuck it does not block all other Flux executions in the same shard (single thread executor) so there are no hickups until one blocks all available threads.

**Comment by OlegDokuka** [comment]
@koldat, as I mentioned this implementation brings huge performance overhead (synchronize + several objects per CF and its stages). In Project Reactor, performance is something we prefer to set as a first-class citizen in most of the scenarios. Thus such overhead is something we need to care about since Scheduler is usually a hot-path.

Please, let me know if would like to continue working on that and rework the current effort into the Trampolin version. Otherwise, we will take care of that.

Thanks

**Pull request closed without merging**
