### PR TITLE
Marbles Inkscape Migration

### PR DESCRIPTION
**Pull request by thekalinga**
Migrated almost all marbles from existing format to Inkscape

Additional Notes:

1. Modified many existing marble diagrams
2. Added many new marble diagrams
3. There are two files `coreFeatures.adoc` & `advancedFeatures.adoc` that refer to files in `https://raw.githubusercontent.com/reactor/reactor-core/v3.0.7.RELEASE/src/docs/marble/*.png` format. I have not migrated these
4. Updated `README.md` to use `doc-files/optimized` folder instead of `https://raw.githubusercontent.com/reactor/reactor-core/..`
5. `Operators.serialize` does not have any marble now as I could not find any corresponding one in older marbles folder

### CODE REVIEW

**Comment by thekalinga** [comment]
@simonbasle Created pull request by taking into account the reorganization changes you made

**Comment by simonbasle** [comment]
@thekalinga I think that is a fine tradeoff, the end goal here is to have the optimized marble diagrams embedded into the javadoc jar.

other images are fine for now, and it should be much easier to later embed images and other assets in the reference guide zip file.

**Comment by thekalinga** [comment]
@simonbasle I think we have remove all colors for signals that does not actually use a scheduler. If I look at these with new eyes it quite confusing

Unless we have a scheduler involved (or) the arguments of an operator are colored, all arrows should be of the same color as downstream signals

**Comment by thekalinga** [comment]
@simonbasle Corrected issues with few marble diagrams. Please get the latest source from the repo

**Comment by thekalinga** [comment]
@simonbasle Fixed issues within `withLatestFrom` marble diagram

**Comment by simonbasle** [comment]
I'm not really happy with the overall state of this PR, which contains far too many different changes. The work on producing SVG is outstanding and appreciated, but reviewing this PR has been quite difficult, and I'm not happy with the script/process here.

@thekalinga if you are ok with it, I'll take it from here and extract the SVG content of the patch + the javadoc img changes (and **only** these changes, removing most unrelated `</p>` changes and the like) and do a PR myself. Of course, I'll set you as author on the commit that introduces the SVGs.

**Comment by thekalinga** [comment]
@simonbasle Back from a small break. Sure, feel  free to do what you feel is appropriate on this.

w.r.t modifications, I'll let you be the judge of what you think is most intuitive for each of the marbles

Please let me know if you need me to do any changes to any of these files

**Comment by thekalinga** [comment]
Closing in favor of https://github.com/reactor/reactor-core/pull/1390

**Pull request closed without merging**
