### PR TITLE
Fix a few return types in Mono javadocs

### PR DESCRIPTION
**Pull request by seants**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@seants Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2581)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2581) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by seants** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@seants This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by simonbasle** [comment]
From #2577 it looks like `master` had even more occurrences. I'll take that into account when forward-merging this change.

**Review by simonbasle — CHANGES_REQUESTED** [review]
thanks for the fix. looks like `subscribeOn` is also referencing the wrong return type.

**Comment by seants** [comment]
Ah thanks must've gotten lost in the merge. Not sure how to retrigger the failed tests

**Comment by simonbasle** [comment]
> Not sure how to retrigger the failed tests

I triggered a re-run

**Review by simonbasle — APPROVED** [review]

**Comment by simonbasle** [comment]
forward-merged to `master` (3.4.3) and fixed the two additional cases in the merge commit (`Mono.timed` and `Mono.metrics`)

**Comment by seants** [comment]
thanks!

**Pull request merged**
