### PR TITLE
fix #1283 Add log variant with value mapper

### LINKED ISSUE #1283: add log method with custom log message
Using the `log` method is often the best way to understand the flow of data, but the log messages sometimes contain too much noise. Therefore it would be useful to be able to customize the log output.

## Current Behavior

In the following (Kotlin) example the class `Message` contains meta data fields not relevant to understand the logic:

```kotlin
data class Message<T>(
        val value: T,
        val timestamp: Instant,
        val quality: Int,
        val source: String)

val source = Flux.just(
        Message(1, Instant.now(), 99, "A"),
        Message(2, Instant.now(), 98, "B"),
        Message(3, Instant.now(), 97, "A"))

source.filter { it.value > 1 }.log("category").subscribe()
```

The output would be

```
13:17:52.726 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
13:17:52.770 [main] INFO  category - | onSubscribe([Fuseable] FluxFilterFuseable.FilterFuseableSubscriber)
13:17:52.773 [main] INFO  category - | request(unbounded)
13:17:52.774 [main] INFO  category - | onNext(Message(value=2, timestamp=2018-07-18T11:17:51.010Z, quality=98, source=B))
13:17:52.810 [main] INFO  category - | onNext(Message(value=3, timestamp=2018-07-18T11:17:51.010Z, quality=97, source=A))
13:17:52.811 [main] INFO  category - | onComplete()
```
## Behavior of new `log` method

But I'd like to be able to print only the `value` of the `Message` class. So I'd need a variant of the `log` method, something like this:

```kotlin
source.filter { it.value > 1 }.log("category") { it.value }.subscribe()
```

or in Java

```java
source.filter(message -> message.value > 1).log("category", message -> message.value).subscribe()
```

The output should be:

```
13:17:52.726 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
13:17:52.770 [main] INFO  category - | onSubscribe([Fuseable] FluxFilterFuseable.FilterFuseableSubscriber)
13:17:52.773 [main] INFO  category - | request(unbounded)
13:17:52.774 [main] INFO  category - | onNext(2)
13:17:52.810 [main] INFO  category - | onNext(3)
13:17:52.811 [main] INFO  category - | onComplete()
```

The function parameter of the `log` method should have the type `T -> Object` and the `Object` should then be rendered as `String`.

### PR DESCRIPTION
**Pull request by simonbasle**
@smaldini wdyt? Maybe keeping only the mapper only + mapper;logger/category;Level variants? (removing 2 extra overrides)

### CODE REVIEW

**Comment by smaldini** [comment]
It’s a bit much imo especially compared to a a doOnSignal. Also, should the formatting come from the logger itself ?

**Comment by simonbasle** [comment]
can you clarify that last sentence?

**Comment by smaldini** [comment]
The issue is related to formatting the message, Logger can itself prettyprint specific payload (like what SLF4J tries to do with collections). I think we shouldn't merge this right away and collect more feedback but my gut feeling is that it's a step too much for log() operator.

**Comment by simonbasle** [comment]
ok, abandoning this as explained in the issue

**Pull request closed without merging**
