### PR TITLE
Off-by-one in error message

### PR DESCRIPTION
**Pull request by nurkiewicz**
Still poor grammar

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nurkiewicz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1321)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=1321) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@nurkiewicz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=1321)!

**Comment by simonbasle** [comment]
Since 3.2 is around the corner, this could be a good opportunity to slightly change the message's wording? In order to correctly reflect the `i` that caused an issue and avoid mental gymnastics when debugging, how about this one:

```
"Source Publisher #" + i + " is null"
```

**Comment by szpak** [comment]
I like the idea with `#X`. An error message should be short & simple.

**Comment by simonbasle** [comment]
We appreciate the PR @nurkiewicz. I have edited it to still reflect the index variable `i`. What do you think?

**Pull request merged**
