### PR TITLE
Update debugging.adoc

### PR DESCRIPTION
**Pull request by libinglong**
do u mean capabilities?Im not good at English

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@libinglong Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2449)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=2449) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@libinglong Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=2449)!

**Review by simonbasle — APPROVED** [review]
that is indeed a typo, thanks @libinglong !
I'll retarget on 3.3.x branch where the typo was introduced and merge.

**Comment by simonbasle** [comment]
eh, you used `master` as your branch for that change in your fork, which makes editing this and rebasing on top of 3.3.x a headache. consider creating "feature branches" when you submit PRs instead of working on a direct mirror of the existing maintenance branches.

I'll fix that separately, this is just a simple polish. Thanks for reporting in any case @libinglong

**Pull request closed without merging**
