### PR TITLE
makes error handling for fmSequential consistent with flatMap

### LINKED ISSUE #3396: Inconsistent error handling with flatMap vs flatMapSequential
We have 2 pieces of code that runs some code that throws. In the working-as-expected case, we use flatMap and in the other case, we use flatMapSequential.

## Expected Behavior
Downstream operators shouldn't be affected by whether we use flatMap or if we use flatMapSequential.

## Actual Behavior
Using .flatMapSequential followed by onErrorContinue throws `ErrorCallbackNotImplemented` instead.

## Steps to Reproduce
This is working as expected:
```java
Flux.range(1, 5)
    .flatMap(i -> Mono.defer(() -> {
        throw new RuntimeException("Error on " + i);
    }))
    .onErrorContinue((t, o) -> {
        log.error("This is called here as expected.", t);
    })
    .subscribe();
```

This other case throws `ErrorCallbackNotImplemented`:
```java
Flux.range(1, 5)
    .flatMapSequential(i -> Mono.defer(() -> {
        throw new RuntimeException("Error on " + i);
    }))
    .onErrorContinue((t, o) -> {
        log.error("This is not called at all.", t);
    })
    .subscribe();
```

The only difference is flatMapSequential instead of flatMap.
## Your Environment

* Reactor version(s) used: Tested on 3.4.12 & 3.5.3
* JVM version (`java -version`): OpenJDK "17.0.1" 2021-10-19 LTS
* OS and version (eg `uname -a`): MacOS Darwin 22.1

### PR DESCRIPTION
**Pull request by eralmansouri**
closes #3396

### CODE REVIEW

**Comment by OlegDokuka** [comment]
Thanks for the PR, @eralmansouri! Awesome job!
Can you please include a test from the original issue to prove all work fine?

Thanks,
Oleh

**Comment by eralmansouri** [comment]
@OlegDokuka I added a test to show it works. It is slightly ugly because I couldn't use AssertSubscriber here.

**Review by OlegDokuka — APPROVED** [review]

**Comment by OlegDokuka** [comment]
@eralmansouri can you please rebase your PR on 3.4.x

**Comment by eralmansouri** [comment]
@OlegDokuka 

Ok rebased onto 3.4.x

**Comment by OlegDokuka** [comment]
congrats @eralmansouri on your first merged PR 🎉! 
Good work. Keep it up! 

Look forward to seeing more fixes from you!

**Pull request merged**
