### PR TITLE
Fix the comment for Flux.blockLast() method

### PR DESCRIPTION
**Pull request by TomekJurkowski**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@TomekJurkowski Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=632)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=632) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by simonbasle** [comment]
@pivotal-issuemaster this is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@TomekJurkowski Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=632)!

**Comment by simonbasle** [comment]
Thanks for the typo fix @TomekJurkowski

**Comment by simonbasle** [comment]
Note this is a simple enough change (typo in javadoc) that you don't need to sign the CLA this time.

**Pull request merged**
