### PR TITLE
typo operatorStacktrace misspeld

### PR DESCRIPTION
**Pull request by bodtx**
When testing in my IDE `operatorStackTrace` does not exist

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@bodtx Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=506)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-core&pullRequestId=506) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by bodtx** [comment]
Contributor License Agreement, signed ✅

**Comment by pivotal-issuemaster** [comment]
@bodtx Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-core&pullRequestId=506)!

**Comment by smaldini** [comment]
Thanks a lot !

**Pull request merged**
